### ISSUE TITLE
Error syncing gradle with firebase-auth dependency KMPP

### ISSUE THREAD

**Issue by Fed93** [GitLiveApp/firebase-kotlin-sdk#102]
I'm trying to use the library in a KMPP project and i'm trying to add Firebase auth library to commonMain.
When i add it in commonMain dependencies gradle give me this error:

`<ij_msg_gr>Gradle import errors<ij_msg_gr><ij_nav>{projectPath}\core\build.gradle.kts<ij_nav><i><b>project ':core': Unable to build Kotlin project configuration</b><eol>Details: org.gradle.internal.operations.BuildOperationQueueFailure: There was a failure while populating the build operation queue: Could not find firebase-auth-1.0.0-samplessources.jar (dev.gitlive:firebase-auth:1.0.0).<eol>Searched in the following locations:<eol>    https://jcenter.bintray.com/dev/gitlive/firebase-auth/1.0.0/firebase-auth-1.0.0-samplessources.jar<eol>Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find firebase-auth-1.0.0-samplessources.jar (dev.gitlive:firebase-auth:1.0.0).<eol>Searched in the following locations:<eol>    https://jcenter.bintray.com/dev/gitlive/firebase-auth/1.0.0/firebase-auth-1.0.0-samplessources.jar</i>`

If i add the dependencies only to androidMain, for example, gradle sync successful but i can use the library only in Android folders correctly.

I'm using Gradle 6.5 with Gradle kts and i'm adding dependency like this:
`implementation("dev.gitlive:firebase-auth:1.0.0")`

in commonMain SourceSet, like that:
```
val commonMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlin:kotlin-stdlib-common")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines}")

                // Http
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:${Versions.serialization}")
                implementation("io.ktor:ktor-client-core:${Versions.ktor}")
                implementation("io.ktor:ktor-client-serialization:${Versions.ktor}")
                implementation("io.ktor:ktor-client-logging:${Versions.ktor}")

                implementation("dev.gitlive:firebase-auth:1.0.0")
            }
        }
```

**Comment by Fed93** [comment]
I've also tried with older versione for example version 0.4.0 and is working correctly as commonMain dependency

**Comment by Reedyuk** [comment]
A couple of questions, what version of kotlin are you using?

Can you produce a sample repo with the issue?

I notice someone else had a similar issue with ktor:
https://youtrack.jetbrains.com/issue/KTOR-1100?_ga=2.211235612.885491558.1604927663-159726149.1604585200

**Comment by Fed93** [comment]
I'm on Kotlin 1.4.10

I'll make you ASAP a sample repo, also i'll try to update gradle version may it will resolve the problem.
Thanks for you response with the bug tracked on YouTrack, when i've tried to search something on Google about the error it gave me no match. Maybe too much detail in my research!

**Comment by Fed93** [comment]
Hi @Reedyuk, i've attached an example to allow you to reproduce the problem.
I've also tried with Gradle 6.7 but the problem is the same.

[Example.zip](https://github.com/GitLiveApp/firebase-kotlin-sdk/files/5513288/Example.zip)

**Comment by Fed93** [comment]
Hi @Reedyuk, is there any news about this issue?

**Comment by Reedyuk** [comment]
Hi @Fed93 - sorry i haven't had chance yet, thanks for the reminder, if i get a moment this evening, i will have a look for you.

**Comment by Reedyuk** [comment]
@Fed93 first thing that shouts out at me is this in the gradle properties:
```
kotlin.js.compiler=ir
```
Can you comment this out and see if it works? I couldn't fully test at the moment as I have just switched over to a new Apple M1 and I have other issues compiling.

**Comment by Fed93** [comment]
Oh wow, this was the issue! 
This is so strange with version 0.4.0 the issue never occured. 
No problem about removing ir compiler.. it was only for testing new Kotlin compiler for Kotlin/JS.
Thank you!

**Comment by Reedyuk** [comment]
![jedi](https://user-images.githubusercontent.com/3853006/100452774-b4776400-30b1-11eb-8035-a5db8526cd57.gif)
