### ISSUE TITLE
iOS app build issue

### ISSUE THREAD

**Issue by heckslam** [GitLiveApp/firebase-kotlin-sdk#105]
Hello, thanks for the library.

I have created a KMM project (using 1.4.10 and the new android studio plugin) and getting on alright with the Android side. 
Added new dependency to commonMain (`implementation("dev.gitlive:firebase-auth:1.0.0")`) and now when I try to build iOS app it shows the following error:
```
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/user/StudioProjects/testKmmFirebase/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/Script-7555FFB5242A651A00829871.sh
(1 failure)
```

Android app works as expected.
Android Studio version: 4.1.1

**Comment by nbransby** [comment]
@Daeda88 @thoutbeckers do you guys have this issue?

**Comment by thoutbeckers** [comment]
This is just the gradle task (from the KMM project) failing when run from Xcode, not an actual issue. Could be a lot of things. Somewhere Xcode is dumping the actual output of the gradle task with the actual error.

But we use the `auth` artifact on iOS successfully, so it should be possible to make it work.

**Comment by heckslam** [comment]
I tried to run it from Xcode and Android studio. The error message is the same for both cases. Which version of the library you are using?

**Comment by rocketraman** [comment]
I have the same problem with my gradle build on iOS after updating to 1.0.0. In my case, the gradle daemon consistently dies, and without any error messages:

```
[... some compiler warnings (no errors)...]
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=c8792bd7-5af3-4c02-bf85-cfcc33bfdd87, currentDir=/Users/raman/source/foo/iosApp/Pods}
Attempting to read last messages from the daemon log...
Daemon pid: 6471
  log file: /Users/raman/.gradle/daemon/6.7.1/daemon-6471.out.log
----- Last  20 lines from daemon log file - daemon-6471.out.log -----
[...same warnings as above, no other useful errors]
----- End of the daemon log -----
```

Using Gradle 6.7.1, JDK 11 for the build.

**Comment by heckslam** [comment]
solution in #111
