### ISSUE TITLE
Add FirebaseUser.idToken with claims to firebase-auth

### ISSUE THREAD

**Issue by rocketraman** [GitLiveApp/firebase-kotlin-sdk#107]
| Library               | Class                            | Member                                        | Platforms                  |
| :-----------------| :------------------------ | :----------------------------------- | :---------------------- |
| user | FirebaseAuth | idToken  | Android, iOS  |

The current version of `idToken` returns only the token itself. The underlying library does provide access to the claims present in the token via the claims property on both iOS and Android. It would be nice if there was a way to get those claims without having to parse the token again.

Reference documentation for APIs in question:

Android: https://firebase.google.com/docs/reference/android/com/google/firebase/auth/GetTokenResult#getClaims()

iOS: https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Classes/AuthTokenResult#claims

Note that both platforms provide some additional convenience properties as well, such as the auth timestamp, expiration timestamp, issued at timestamp, and sign-in provider. Ideally, all of those would be available, but from my perspective the claims are the most important and any other attribute should be obtainable from the claims.

**Comment by nbransby** [comment]
Could you paste in links to the API you are referring to?

**Comment by rocketraman** [comment]
> Could you paste in links to the API you are referring to?

@nbransby I've updated the original post with the API reference links.
