### ISSUE TITLE
[FireStore] How to decode Timestamp in Multiplatform Code (Android/iOS)

### ISSUE THREAD

**Issue by wezley98** [GitLiveApp/firebase-kotlin-sdk#113]
### Given
```
data class Article(
    val title: String = "",
    val subTitle: String = "",
    val image: String = "",
    val date: Double = 0.0,
    val content: String = ""
)

Firebase.firestore.collection("articles")
            .get()
            .documents
            .map { doc ->
                Article(
                    doc.get("title"),
                    doc.get("subTitle"),
                    doc.get("image"),
                    doc.get("date"),
                    doc.get("content")
                )
            }
```
### When
`date` is type timestamp in Firestore.

### Then
How do we decode this type in commonMain for example? I have tried setting Article.date to String and Double and both crash.

```
 kotlinx.serialization.SerializationException: Expected Timestamp(seconds=1606944088, nanoseconds=0) to be double
```

Does the SDK provide any method to help with decoding this automatically?

**Comment by nbransby** [comment]
Yes, have a read of https://github.com/GitLiveApp/firebase-kotlin-sdk#serialization

**Comment by wezley98** [comment]
@nbransby Thanks for the reply, I had already read the docs, I couldn't find anywhere to pass in the Class serializer for Article as .get() doesn't take any parameters the same way set() would. We are trying to read data from Firestore.

` suspend fun get(): QuerySnapshot`

**Comment by nbransby** [comment]
```
@Serializable
data class Article(
    val title: String = "",
    val subTitle: String = "",
    val image: String = "",
    val date: Double = 0.0,
    val content: String = ""
)

Firebase.firestore.collection("articles")
            .get()
            .documents
            .map { doc -> doc.data(City.serializer())  }
```

**Comment by nbransby** [comment]
Or you might be affected by https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/64 ?

**Comment by wezley98** [comment]
@nbransby Thanks for the code, I just tried that exact sample code in Android and still get,

```
kotlinx.serialization.SerializationException: Expected Timestamp(seconds=1606944088, nanoseconds=0) to be double
```

**Comment by matanmarciano** [comment]
@wezley98 any solution?

**Comment by RZahr** [comment]
What about encoding it ? i.e. adding a date in the where clause List<DocumentSnapshot>.where("updatedDate", greaterThan = what_to_place_here)

**Comment by manuelh19** [comment]
> What about encoding it ? i.e. adding a date in the where clause Query.where("updatedDate", greaterThan = what_to_place_here)

Any updates on this?
