### ISSUE TITLE
Sending events

### ISSUE THREAD

**Issue by PokerAsh** [GitLiveApp/firebase-kotlin-sdk#114]
Hello, I would like to know if there is already implemented sending events into firebase console? Or is in plans?

I am seeing that you've already working on analytics, but couldn't find any way of calling them. Would be great if it was in these libraries!

Thanks in advance

**Comment by nbransby** [comment]
Hi @PokerAsh no there hasn't been any work done on analytics yet but we do want to add them at some point in the future and PRs are always welcome!

**Comment by mustafaozhan** [comment]
@nbransby Really interested on analytics implementation 👍 but couldn’t find any issue to follow the progress do you have one or should we subscribe to this issue ?

**Comment by JenniferCabotage** [comment]
Very interested in analytics support!

**Comment by mattdornfeld** [comment]
Same!

**Comment by NathanFallet** [comment]
Interested as well!

**Comment by florianNgbala** [comment]
Interested as well !
