### ISSUE TITLE
Please add orderBy option for collection (Firestore)

### ISSUE THREAD

**Issue by matanmarciano** [GitLiveApp/firebase-kotlin-sdk#116]
Hi, I am using Kotlin Multi Platform SDK, in the commonMain - there is no orderBy on `val usersCollection = firebaseFirestore.collection("Users")`

am I missing something?

**Comment by matanmarciano** [comment]
@nbransby

**Comment by matanmarciano** [comment]
@nbransby @CoreyKaylor 
can you help me? I need a solution asap

**Comment by nbransby** [comment]
@matanmarciano workaround is to create an expect/actual extension function in your own code and use https://github.com/GitLiveApp/firebase-kotlin-sdk#accessing-the-underlying-firebase-sdk

**Comment by nbransby** [comment]
But hasn't this been added already? Here https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/109

Are you using latest version?

**Comment by matanmarciano** [comment]
I was used 1.0.0 because of other reasons, but now I upgrade to 1.1.0 and I see the orderBy functionality. 
BUT how can I get the documents ordered by insertion time? it means server time..it is for chat application

@nbransby

**Comment by nbransby** [comment]
@matanmarciano  how would you do it in the kotlin android sdk?

**Comment by matanmarciano** [comment]
> @matanmarciano how would you do it in the kotlin android sdk?

Just Use the @ServerTimestamp annotation on my 'timestamp' property:
https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/ServerTimestamp

Any solution in your library?
