### ISSUE TITLE
Include Firebase libs inside Kotlin - ios publications (klibs)

### ISSUE THREAD

**Issue by suntrix** [GitLiveApp/firebase-kotlin-sdk#119]
It simplifies the iOS app implementation, because Firebase libs don't need to be added into the app/library anymore (they're already included in klibs).

https://kotlinlang.org/docs/reference/native/c_interop.html#including-static-library-in-your-klib

It should fix issues like #111

**Comment by nbransby** [comment]
PRs welcome on this!

**Comment by suntrix** [comment]
@nbransby After giving this another thought its better to not include these. 

Main reason is more flexibility on the iOS side. 
The iOS app can include newer Firebase SDKs than the multiplatform lib was build with & not require multiplatform lib to be updated.
