### ISSUE TITLE
Add FirebaseAuth.signInWithEmailAndPassword to auth for Android and iOS

### ISSUE THREAD

**Issue by NahroTo** [GitLiveApp/firebase-kotlin-sdk#12]
| Library               | Class                            | Member                                        | Platforms                  |
| :-----------------| :------------------------ | :----------------------------------- | :---------------------- |
| auth | FirebaseAuth | signInWithEmailAndPassword  | Android, iOS  |

**Comment by nbransby** [comment]
Hey, I added this on master, firebase-auth version 0.2.0 - can you clone the repo, publish to maven local and see if it works for you? Once you confirm we can publish it to maven central.
