### ISSUE TITLE
Please expose docChanges() for Firestore SDK

### ISSUE THREAD

**Issue by matanmarciano** [GitLiveApp/firebase-kotlin-sdk#122]
Reference: https://github.com/GitLiveApp/firebase-kotlin-sdk/discussions/115#discussioncomment-219985

Many thanks

**Comment by matanmarciano** [comment]
@nbransby Wow, thanks for the responsibly!
When you will release this version?

**Comment by nbransby** [comment]
Next week

**Comment by matanmarciano** [comment]
> Next week

Still not released? I see 1.2.0 released and I did found doChanges capability
@nbransby

**Comment by nbransby** [comment]
Yes it should be there, called documentChanges
