### ISSUE TITLE
framework not found FirebaseAuth when build to ios

### ISSUE THREAD

**Issue by liemdovan** [GitLiveApp/firebase-kotlin-sdk#133]
Hi, I tried to build Gradle to ios but it appears  
![Screen Shot 2021-01-05 at 11 09 42](https://user-images.githubusercontent.com/76475243/103605511-a20d0780-4f46-11eb-9a1f-2a40c5c29c9a.png)

This is my build Gradle file
`kotlin {
    targets {
        fromPreset(presets.android, 'android')

        def iosPreset = presets.iosX64
        fromPreset(iosPreset, 'ios') {
            binaries {
                framework {
                    //framework("VibeChallengeSDK")
                    // Disable bitcode embedding for the simulator build.
                    if (iosPreset == presets.iosX64) {
                        embedBitcode("disable")
                    }
                }
            }
            //compilations.main.outputKinds('VibeChallengeSDK')
            compilations.each {
                //it.extraOpts("-linkerOpts", "-lsqlite3")
            }
        }
    }

    sourceSets {
        commonMain.dependencies {
            api 'org.jetbrains.kotlin:kotlin-stdlib-common'

            implementation "org.jetbrains.kotlin:kotlin-stdlib-common:$kotlin_version"

            // COROUTINE
            implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:$coroutine_version"

            // SERIALIZATION
            implementation "org.jetbrains.kotlinx:kotlinx-serialization-core:1.0.0-RC"

            // KTOR
            implementation "io.ktor:ktor-client-core:$ktor_version"
            implementation "io.ktor:ktor-client-serialization:$ktor_version"

            //  PREFERENCES
            implementation "com.github.florent37:multiplatform-preferences:1.0.0"

            //KODEIN
            implementation 'org.kodein.di:kodein-di:7.1.0'

            // MOKO - MVVM
            implementation "dev.icerock.moko:mvvm:$moko_mvvm_version"

            // FIRE STORE
            implementation "co.touchlab:firestore:0.2.5"
            implementation "dev.gitlive:firebase-auth:1.1.0"
            implementation "dev.gitlive:firebase-database:1.1.0"
            implementation "dev.gitlive:firebase-functions:1.1.0"

            // JSON CONVERTER
            implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.1")
            implementation("com.google.code.gson:gson:2.8.2")
        }

        androidMain.dependencies {
            //api 'org.jetbrains.kotlin:kotlin-stdlib'
            implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

            implementation "org.jetbrains.kotlin:kotlin-stdlib-common:$kotlin_version"

            // COROUTINE
            implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutine_version"
            implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutine_version"

            // SERIALIZATION
            //implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serializer_version"

            // KTOR
            implementation "io.ktor:ktor-client-android:$ktor_version"

            //PREFERENCES
            implementation "com.github.florent37:multiplatform-preferences-android:1.0.0"

            // MOKO - MVVM
            implementation "androidx.lifecycle:lifecycle-extensions:$androidx_lifecycle_version"
        }

        iosMain.dependencies {
            implementation "org.jetbrains.kotlin:kotlin-stdlib-common:$kotlin_version"

            // COROUTINE
            implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-native:$coroutine_version"

            // SERIALIZATION
            //implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:$serializer_version"

            // KTOR
            implementation "io.ktor:ktor-client-ios:$ktor_version"
        }

        commonTest {
            dependencies {
                implementation kotlin('test-common')
                implementation kotlin('test-annotations-common')
                implementation "io.mockk:mockk:$mockk_version"
            }
        }

        androidTest {
            dependencies {
                implementation kotlin('test')
                implementation kotlin('test-junit')
                implementation 'com.android.support.test:runner:1.0.2'

                // actually not needed, see https://youtrack.jetbrains.com/issue/KT-31189
                //implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serializer_version"
                implementation "com.soywiz:klock-android:$klock_version"

                implementation "io.mockk:mockk:$mockk_version"
            }
        }

    }
}
`

Please help thank you

**Comment by urgentx** [comment]
Same issue for me, shared build.gradle: 

```
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

plugins {
    kotlin("multiplatform") version "1.4.10"
}

group = "com.mobird"
version = "1.0-SNAPSHOT"

kotlin {
    ios {
        binaries {
            framework {
                baseName = "shared"
            }
        }
    }
    sourceSets {
        val commonMain by getting {
            dependencies {
                api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2-native-mt")
                implementation("dev.gitlive:firebase-firestore:1.2.0")
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
            }
        }
        val iosMain by getting
        val iosTest by getting
    }
}

val packForXcode by tasks.creating(Sync::class) {
    group = "build"
    val mode = System.getenv("CONFIGURATION") ?: "DEBUG"
    val sdkName = System.getenv("SDK_NAME") ?: "iphonesimulator"
    val targetName = "ios" + if (sdkName.startsWith("iphoneos")) "Arm64" else "X64"
    val framework = kotlin.targets.getByName<KotlinNativeTarget>(targetName).binaries.getFramework(mode)
    inputs.property("mode", mode)
    dependsOn(framework.linkTask)
    val targetDir = File(buildDir, "xcode-frameworks")
    from({ framework.outputDirectory })
    into(targetDir)
}

tasks.getByName("build").dependsOn(packForXcode)

**Comment by suntrix** [comment]
You need to add iOS frameworks to your project. See comments in #111

**Comment by urgentx** [comment]
@suntrix Thank you. The cocoapods method did not work, but using Carthage did.
