### ISSUE TITLE
Add FirebaseApp.initialize to firebase.common for all platforms

### ISSUE THREAD

**Issue by Lamartio** [GitLiveApp/firebase-kotlin-sdk#141]
Hey all!,

Thanks for creating this amazing wrapper! I run into an issue though: When I want to login (on web), I get the error: `Error: Be sure to include authDomain when calling firebase.initializeApp(), by following the instructions in the Firebase console.`. This is the snippet that caused the error:
```
Firebase
    .auth(app)
    .js
    .signInWithPopup(firebase.auth.GoogleAuthProvider())
    .await()
```

When I initialize the app I am missing the option `authDomain` in the `dev.gitlive.firebase.FirebaseOptions`. Could you at this property to the object? 

| Library               | Class                            | Member                                        | Platforms                  |
| :-----------------| :------------------------ | :----------------------------------- | :---------------------- |
| common | FirebaseApp | initializeApp | all |

**Comment by mihbor** [comment]
Encountered this issue when trying to do the same.
I suggest renaming this issue to "add authDomain to FirebaseOptions" for easier discoverability.

**Comment by mihbor** [comment]
I made a stab at a PR to add authDomain to FirebaseOptions (above). I haven't managed to get master to build locally I'm afraid, so I wasn't able to test this either.
