### ISSUE TITLE
Add (Collection/Document)Reference.snapshotsFor<T>() to Firestore for Android (& iOS?)

### ISSUE THREAD

**Issue by THEAccess** [GitLiveApp/firebase-kotlin-sdk#148]
| Library   | Class                       | Member                                 | Platforms         |
|:---------:|:--------------------:|:------------------------------:|:----------------:|
| firestore | CollectionReference | snapshotsFor<T>() : Flow<List<T>> | Android (iOS?) |
| firestore | DocumentReference | snapshotsFor<T>() : Flow<T> | Android (iOS?) |

CollectionReference already exposes `val snapshots` which is great, but it's not convenient for type-safe mapping to serializable Objects. A direct serialization like `CollectionReference#add` does is needed

**Comment by THEAccess** [comment]
I have cloned the repository and was able to implement it using the following code. It's very simple. Unfortunately, **I cannot build the whole project on my computer (Windows) and start a pull request.**

_CollectionReference_
```kotlin
inline fun <reified T : Any> snapshotsFor(): Flow<List<T>> = snapshots.map {
        it.documents.map { documentSnapshot ->
            decode(documentSnapshot.android.data)
        }
}
```
_DocumentReference_
```kotlin
inline fun <reified T> snapshotsFor(): Flow<T> = snapshots.map {
        decode(it.android.data)
}
```
Note: It's not possible to implement these functions with extension functions because _decode_ is internal

**Comment by nbransby** [comment]
Whats wrong with just `snapshots.map { it.data() }` ?
