### ISSUE TITLE
ReferenceError: $module$firebase_app is not defined

### ISSUE THREAD

**Issue by amyu** [GitLiveApp/firebase-kotlin-sdk#152]
Thank you for providing the very best Library!

I'm getting Webpack errors in the following environments

- kotlin 1.4.30
- use library
  + dev.gitlive:firebase-auth
  + dev.gitlive:firebase-firestore

↓This is a sample of the minimum configuration that will cause errors.
https://github.com/amyu/firebae-kotlin-sdk-sample

Please let me know if I've made any mistakes in the setup process.:pray:

↓ Error message
```
webpack-internal:///./kotlin-dce-dev/firebase-kotlin-sdk-sample.js:46 Uncaught ReferenceError: $module$firebase_app is not defined
    at Object.eval (webpack-internal:///./kotlin-dce-dev/firebase-kotlin-sdk-sample.js:46)
    at eval (webpack-internal:///./kotlin-dce-dev/firebase-kotlin-sdk-sample.js:5)
    at eval (webpack-internal:///./kotlin-dce-dev/firebase-kotlin-sdk-sample.js:8)
    at Object../kotlin-dce-dev/firebase-kotlin-sdk-sample.js (firebase-kotlin-sdk-sample.js:1219)
    at __webpack_require__ (firebase-kotlin-sdk-sample.js:30)
    at Object.0 (firebase-kotlin-sdk-sample.js:1330)
    at __webpack_require__ (firebase-kotlin-sdk-sample.js:30)
    at firebase-kotlin-sdk-sample.js:94
    at firebase-kotlin-sdk-sample.js:97
    at webpackUniversalModuleDefinition (firebase-kotlin-sdk-sample.js:9)
```

**Comment by mihbor** [comment]
Hi @amyu, I'm getting the same error. I see you closed this issue. Have you found a solution?

**Comment by amyu** [comment]
Yes...!

https://github.com/amyu/firebae-kotlin-sdk-sample/commit/cc43bf14cff78f980edce93358177edda3fcc326
Please look ↑ Commit

**Comment by amyu** [comment]
@mihbor 

Yes...!

https://github.com/amyu/firebae-kotlin-sdk-sample/commit/cc43bf14cff78f980edce93358177edda3fcc326
Please look ↑ Commit

**Comment by mihbor** [comment]
Thanks @amyu !
That works for me too but requires the use of the lower level sdk that maps straight to javascript, not the nice wrappers that this projects created, so I think it would be good to reopen this in hope it will get fixed.

**Comment by amyu** [comment]
>  it would be good to reopen this in hope it will get fixed.

Thank you. I'll do that. @mihbor

**Comment by Lamartio** [comment]
Hey guys! I ran into the same issue and found a solution for it. You have to add the SerializationStrategy as the first parameter. Here's a snippet demonstrating it:

``` kotlin
val app: FirebaseApp = app
val store = Firebase.firestore(app)
val collection = store.collection("games")
val document = collection.document("123")

document.set(Test.serializer(), Test("123", "456")) // runs fine
document.set(Test("123", "456")) // compiles with error! ReferenceError: $module$firebase_app is not defined
```

This fix is only useful with types that are annotated with @Serialiable. Are there SerializationStrategies available for common types like List, Pair and Map?

**Comment by nbransby** [comment]
> Are there SerializationStrategies available for common types like List, Pair and Map?

Yes please see https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#constructing-collection-serializers

@Lamartio are you sure your issue is the same as @amyu and @mihbor ?

**Comment by 89jd** [comment]
Is there a way to debug this issue? 

I am receiving the same problem

**Comment by nbransby** [comment]
I believe this has been fixed with the update to the modular firebase js sdk
https://firebase.google.com/docs/web/modular-upgrade
