### ISSUE TITLE
Next library release date

### ISSUE THREAD

**Issue by jfreeley** [GitLiveApp/firebase-kotlin-sdk#168]
Hi folks,

Thanks for this library, finding it very useful!

Just checking if is there a release expected soon? There are some changes which have been merged since the 1.2.0 release that I would like to use.

(I popped this message in discussions previously but maybe I should have posted here.)

Thanks

**Comment by nbransby** [comment]
sorry for the delay on this will be publishing it soon

**Comment by nbransby** [comment]
done
