### ISSUE TITLE
Add Exclude Annotation to Realtime Databases for Android & iOS

### ISSUE THREAD

**Issue by julianfalcionelli** [GitLiveApp/firebase-kotlin-sdk#175]
As it exists in Realtime Databases and FireStore in the original SDKs, we need a way to exclude fields from serialization in KMM.

Ref: https://firebase.google.com/docs/reference/android/com/google/firebase/database/Exclude

**Comment by nbransby** [comment]
Can you use @Transient here? https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#transient-properties

**Comment by julianfalcionelli** [comment]
@nbransby the problem is that @transient is also for preventing the java serialization, and I need to send some of those fields through intents inside a bundle, I just need to exclude the serialization for Firebase, I think that's is why the @exclude annotation exists.

**Comment by nbransby** [comment]
I dont believe it is, there are two transient annotations, maybe you are confusing it with kotlin.jvm.Transient?

A property can be excluded from serialization by marking it with the @Transient annotation (don't confuse it with kotlin.jvm.Transient). Transient properties must have a default value

**Comment by julianfalcionelli** [comment]
Yes, you are right, sorry for the confusion, I will close the issue, thanks for the help!
