### ISSUE TITLE
> Task :shared:compileDebugKotlinAndroid CompilationException: Back-end (JVM) Internal error: wrong bytecode generated

### ISSUE THREAD

**Issue by tiagonuneslx** [GitLiveApp/firebase-kotlin-sdk#181]
I'm getting this error when building using firestore....

> Task :shared:compileDebugKotlinAndroid
e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: wrong bytecode generated
  @Lorg/jetbrains/annotations/Nullable;() // invisible
    // annotable parameter count: 1 (visible)
    // annotable parameter count: 1 (invisible)
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
    TRYCATCHBLOCK L0 L1 L2 java/lang/Throwable
    ALOAD 1
    INSTANCEOF com/qmx/kotlinmultiplatform/shared/network/SpaceXApi$insertLaunch$1
    IFEQ L3
    ALOAD 1
    CHECKCAST com/qmx/kotlinmultiplatform/shared/network/SpaceXApi$insertLaunch$1
    ASTORE 35
    ALOAD 35
    GETFIELD com/qmx/kotlinmultiplatform/shared/network/SpaceXApi$insertLaunch$1.label : I
    LDC -2147483648
    IAND
    IFEQ L3
    ALOAD 35
    DUP
    GETFIELD com/qmx/kotlinmultiplatform/shared/network/SpaceXApi$insertLaunch$1.label : I
    LDC -2147483648
    ISUB
    PUTFIELD com/qmx/kotlinmultiplatform/shared/network/SpaceXApi$insertLaunch$1.label : I
    GOTO L4
   L3
    NEW com/qmx/kotlinmultiplatform/shared/network/SpaceXApi$insertLaunch$1
    DUP
    ALOAD 0
    ALOAD 1
    INVOKESPECIAL com/qmx/kotlinmultiplatform/shared/network/SpaceXApi$insertLaunch$1.<init> (Lcom/qmx/kotlinmultiplatform/shared/network/SpaceXApi;Lkotlin/coroutines/Continuation;)V
    ASTORE 35
   L4
    ALOAD 35
    GETFIELD com/qmx/kotlinmultiplatform/shared/network/SpaceXApi$insertLaunch$1.result : Ljava/lang/Object;
    ASTORE 34
   L5
    INVOKESTATIC kotlin/coroutines/intrinsics/IntrinsicsKt.getCOROUTINE_SUSPENDED ()Ljava/lang/Object;
   L6
    LINENUMBER 29 L6
    ASTORE 36
    ALOAD 35
    GETFIELD com/qmx/kotlinmultiplatform/shared/network/SpaceXApi$insertLaunch$1.label : I
    TABLESWITCH
      0: L7
      1: L8
      default: L9
   L7

The source seems to be this line:
`firestore.collection("test").add(Test("Hey"))`
which is called in a suspend function

@Serializable
data class Test(val value: String)

I've tried a long list of versions of kotlin (1.4.21 until 1.5.0) and kotlinx serialization (1.0.1 until 1.2.0), always gets me this error...

**Comment by nbransby** [comment]
hmmm, looks like another bug in kotlin serialisation

**Comment by nbransby** [comment]
closing as should be fixed in lastest version, please reopen if not
