### ISSUE TITLE
Add DocumentSnapshot.entries to Firestore

### ISSUE THREAD

**Issue by brettwillis** [GitLiveApp/firebase-kotlin-sdk#186]
With the current API, there is no way to retrieve unknown fields from a `DocumentSnapshot`, only known fields can be retrieved (e.g. with `contains()` and `get()`).

The `DocumentSnapshot` needs to also expose a map-like API, like below:

```Kotlin
val size: Int
val entries: Set<Pair<String, Any>>
val keys: Set<String>
val values: Collection<Any>
```

This allows enumeration of all fields, not just those known at compile-time.

**Comment by nbransby** [comment]
Thanks @brettwillis could you attach links to the relevant class members from the native firebase sdk reference documentation?

**Comment by brettwillis** [comment]
[`getData()`](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/DocumentSnapshot#getData()) returns a [`Map<String, Any>`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-map/], which allows enumeration of arbitrary keys and values.

You could either implement a Map-like interface directly on the `DocumentSnapshot` class, or implement `getMap()` or something which returns the native `Map<String, Any>`...
