### ISSUE TITLE
Could not find dev.gitlive:firebase-messaging:1.3.1

### ISSUE THREAD

**Issue by brezinajn** [GitLiveApp/firebase-kotlin-sdk#187]
Gradle fails to locate firebase-messaging artefact. `dev.gitlive:firebase-firestore:1.3.1` works fine.
```
Could not find dev.gitlive:firebase-messaging:1.3.1.
Required by:
    project :app
```

**Comment by nbransby** [comment]
I'm afraid this is becuase we haven't even started to add coverage for the messaging APIs 😢

PRs are very much welcome though!
