### ISSUE TITLE
Add CollectionReference.document() to firestore for Android

### ISSUE THREAD

**Issue by brezinajn** [GitLiveApp/firebase-kotlin-sdk#188]
| Library               | Class                            | Member                                        | Platforms                  |
| :-----------------| :------------------------ | :----------------------------------- | :---------------------- |
| firestore | CollectionReference | document()  | Android|

The missing overload is the one without any arguments (without specified documentPath)

**Comment by tiagonuneslx** [comment]
I've created a pull request for this, just to learn how to do it, so I can contribute more in the future.

For those who don't understand the importance of this, you might think: if I wanted to create a new document with an auto ID like this:

```kotlin
firestore.collection("items").document().set(item)
```

I would instead do this:

```kotlin
firestore.collection("items").add(item)
```

But you might want to do something with the document reference **before** adding the item. Like this:

```kotlin
val documentRef = firestore.collection("items").document()
try {
  uploadImageFile("item_${documentRef.id}")
  documentRef.set(item)
} catch (e: Exception) {
  ...
}
```

If you wanted to do this without the CollectionReference.document(), you'd have to provide an id yourself.
