### ISSUE TITLE
Could not find dev.gitlive:firebase-java-sdk:0.3.2

### ISSUE THREAD

**Issue by agatap2** [GitLiveApp/firebase-kotlin-sdk#19]
I'm getting this error while trying to add "dev.gitlive:firebase-auth:0.1.0" to commonMain dependencies.

Could not find dev.gitlive:firebase-java-sdk:0.3.2.
Searched in the following locations:
  - file:/C:/Users/Agata/.m2/repository/dev/gitlive/firebase-java-sdk/0.3.2/firebase-java-sdk-0.3.2.module
  - file:/C:/Users/Agata/.m2/repository/dev/gitlive/firebase-java-sdk/0.3.2/firebase-java-sdk-0.3.2.pom
  - https://repo.maven.apache.org/maven2/dev/gitlive/firebase-java-sdk/0.3.2/firebase-java-sdk-0.3.2.module
  - https://repo.maven.apache.org/maven2/dev/gitlive/firebase-java-sdk/0.3.2/firebase-java-sdk-0.3.2.pom
  - https://jcenter.bintray.com/dev/gitlive/firebase-java-sdk/0.3.2/firebase-java-sdk-0.3.2.module
  - https://jcenter.bintray.com/dev/gitlive/firebase-java-sdk/0.3.2/firebase-java-sdk-0.3.2.pom
  - https://dl.google.com/dl/android/maven2/dev/gitlive/firebase-java-sdk/0.3.2/firebase-java-sdk-0.3.2.module
  - https://dl.google.com/dl/android/maven2/dev/gitlive/firebase-java-sdk/0.3.2/firebase-java-sdk-0.3.2.pom

**Comment by nbransby** [comment]
Are you on the master branch?

**Comment by nbransby** [comment]
Hmm, that dependency shouldn't be required.

@sadevelopment could you find out what's going on here? Also I was looking on https://mvnrepository.com/artifact/dev.gitlive to check the dependencies but all the libraries have the same name, can we fix that too?

**Comment by nbransby** [comment]
@agatap2 I think its because you have a jvm target defined - im assuming you are using this for android but you need to use an android target

**Comment by agatap2** [comment]
This are my targets:
```
targets {
        final def iOSTarget = System.getenv('SDK_NAME')?.startsWith("iphoneos")    \
                                 ? presets.iosArm64 : presets.iosX64

        fromPreset(iOSTarget, 'ios') {
            binaries {
                framework('MultiCore')
            }
        }

        fromPreset(presets.jvm, 'android')
}
```

**Comment by nbransby** [comment]
Yes, so you are using jvm also this looks like the old mutliplatform syntax, what kotlin plugin version you using? Anyway solution is to use android instead of jvm
