### ISSUE TITLE
Add Query. startAt and Query. startAfter to firestore for Android, iOS

### ISSUE THREAD

**Issue by tiagonuneslx** [GitLiveApp/firebase-kotlin-sdk#206]
| Library               | Class                            | Member                                        | Platforms                  |
| :-----------------| :------------------------ | :----------------------------------- | :---------------------- |
| firestore | Query | startAt  | Android, iOS  |
| firestore | Query | startAfter  | Android, iOS  |

**Comment by tiagonuneslx** [comment]
Docs: https://firebase.google.com/docs/firestore/query-data/query-cursors

**Comment by azurlake** [comment]
Also looking for this functionality.

**Comment by tiagonuneslx** [comment]
> Also looking for this functionality.

I've submited a PR (#219).

But it's missing the tests. I'll see if I will have the time to complete the PR with tests at some point, but I encourage you to do it, if you need the functionality 🙂

**Comment by tiagonuneslx** [comment]
@nbransby PR #219 is awaiting review

**Comment by nbransby** [comment]
closing as now merged in
