### ISSUE TITLE
Contribution questions, adding Analytics

### ISSUE THREAD

**Issue by Nikola-Milovic** [GitLiveApp/firebase-kotlin-sdk#207]
I've been trying to add analytics to the library, has been a smooth integration so far. But stumbled upon a couple of questions that I'd be grateful if anyone could clarify. (porting this from discussions)

1) How can I perform the cinterop task to create the bindings for the library modules?
 The gradle tasks cinteropLibrary create the cart file resolved, and the Carthage folder under the cinterop, but from the other libraries it seems that it gets generated in the iosMain. I may have missed an argument or something to generate it properly. As I cannot access the `import cocoapods.firebase...` 

2) What's the idea behind js part of the libraries? I see that the declarations are provided in the `firebaseCommon/jsMain/externals.kt` but the actual implementation and functionality is anywhere to be seen? 

Is there anything else I should be aware of?

**Comment by ynsok** [comment]
Any update about it ?  😄

**Comment by Nikola-Milovic** [comment]
Unfortunately, I moved away from the library and had some manual integration with Firebase. But that project has been long deprecated
