### ISSUE TITLE
Cache downloadIOSFirebaseZipFile

### ISSUE THREAD

**Issue by vanniktech** [GitLiveApp/firebase-kotlin-sdk#21]
Every time I'm executing `publishToMavenLocal` I'm downloading 1GB:

```
> Task :downloadIOSFirebaseZipFile
Download https://github.com/firebase/firebase-ios-sdk/releases/download/6.17.0/Firebase-6.17.0.zip
```

Can we cache that file?

**Comment by nbransby** [comment]
It only downloads it if its not already been downloaded already. Maybe you are doing a clean build?

**Comment by vanniktech** [comment]
Nope. I'm executing `gradle publishToMavenLocal`.

**Comment by nbransby** [comment]
Its this line that stops it repeating itself:
https://github.com/GitLiveApp/firebase-kotlin-sdk/blob/13b510c448f4847b5adc9d89774d45cd2f6d2707/build.gradle.kts#L39
Means you need to wait for it to unzip before it will skip, have you let it download and unzip or do you cancel it each time?

**Comment by vanniktech** [comment]
It is downloaded over and over again. (Unzipping works). Also, usually Gradle tasks need both input & outputs in order to be up to date.

**Comment by nbransby** [comment]
Strange cant reproduce, @sadevelopment might be able to help otherwise would appreciate a PR!

**Comment by vanniktech** [comment]
Okay so I might got have a hint:

I was doing:

```
cd REPO
cd firebase-auth
gradle publishToMavenLocal
```

(since firebase store / database could not be built) now that this is fixed I can execute `publishToMavenLocal` from the root as well and I'm no longer seeing the SDK being downloaded repeatedly.

**Comment by nbransby** [comment]
@sadevelopment could you fix?
