### ISSUE TITLE
Using this sdk in a web app with Jetpack compose?

### ISSUE THREAD

**Issue by Nikola-Milovic** [GitLiveApp/firebase-kotlin-sdk#213]
If anyone has succeeded in getting this library to work properly for the web I'd love to hear what versions you're using and what setup do you have. It seems that the library only works with legacy JS compiler, I had it forked and made it work with IR but then I was having this error 

```
> Task :web-app:compileDevelopmentExecutableKotlinJs FAILED
e: Module <dev.gitlive:firebase-auth> is a module[ModuleDescriptorImpl@62ac83c2] has reference public dev.gitlive.firebase.auth/FirebaseUser.displayName.<get-displayName>|-7122534302014937473[1], unfortunately neither itself nor its dependencies [
        org.jetbrains.kotlin.ir.backend.js.lower.serialization.ir.JsIrLinker$JsModuleDeserializer@5b30eb79
        org.jetbrains.kotlin.ir.backend.js.lower.serialization.ir.JsIrLinker$JsModuleDeserializer@17c9428e
        
org.jetbrains.kotlin.ir.backend.js.lower.serialization.ir.JsIrLinker$JsModuleDeserializer@4974c
        org.jetbrains.kotlin.backend.common.serialization.IrModuleDeserializerWithBuiltIns@5d0478f0
] contain this declaration
Please check that project configuration is correct and has required dependencies.
```

After which I switched to react and legacy compiler with `useCommonJs`

```
kotlin {
    js {
        useCommonJs()
        browser()
}
```

I was wondering if anyone successfully go everything to work and what versions were they using for the common libraries like compose, kotlin, coroutines, ktor and such.

**Comment by shepeliev** [comment]
@Nikola-Milovic I've been succeeded with IR compiler. Try to remove default args in `updateProfile()` method at `dev/gitlive/firebase/auth/user.kt`
