### ISSUE TITLE
Compatibility with JVM only?

### ISSUE THREAD

**Issue by BenjaminHolland** [GitLiveApp/firebase-kotlin-sdk#216]
I'm a bit confused, do I need to be using the multiplatform kotlin plugin to use this library, or can I use one of the specific platform plugins like jvm?

**Comment by suntrix** [comment]
Technically you can use non-multiplatform Kotlin plugin with the same artifact names as for multiplatform, because the plugin will try to find the right artifact variant for you. Unfortunately there's no JVM target in this lib yet, only Android.
