### ISSUE TITLE
Error compiling kotlin for ios "Could not resolve dev.gitlive:firebase-auth:1.3.1."

### ISSUE THREAD

**Issue by AlexWink** [GitLiveApp/firebase-kotlin-sdk#218]
Hello, I've encountered the package download error with the version 1.4.2 but even with the 1.3.1, I can't find a way to launch the ios project as I face this issue:

``Execution failed for task ':shared:compileKotlinIos'.
> Could not resolve all files for configuration ':shared:iosCompileKlibraries'.
   > Could not resolve dev.gitlive:firebase-auth:1.3.1.
     Required by:
         project :shared
      > No matching variant of dev.gitlive:firebase-auth:1.3.1 was found. The consumer was configured to find a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native', attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64' but:
          - Variant 'debugApiElements-published' capability dev.gitlive:firebase-auth:1.3.1 declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_simulator_arm64')
          - Variant 'debugRuntimeElements-published' capability dev.gitlive:firebase-auth:1.3.1 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_simulator_arm64')
          - Variant 'iosArm64ApiElements-published' capability dev.gitlive:firebase-auth:1.3.1 declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64'
          - Variant 'iosX64ApiElements-published' capability dev.gitlive:firebase-auth:1.3.1 declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_x64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64'
          - Variant 'jsApiElements-published' capability dev.gitlive:firebase-auth:1.3.1 declares a usage of 'kotlin-api' of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_simulator_arm64')
          - Variant 'jsRuntimeElements-published' capability dev.gitlive:firebase-auth:1.3.1:
              - Incompatible because this component declares a usage of 'kotlin-runtime' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js' and the consumer needed a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_simulator_arm64')
          - Variant 'metadataApiElements-published' capability dev.gitlive:firebase-auth:1.3.1 declares a usage of 'kotlin-api' of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_simulator_arm64')
          - Variant 'releaseApiElements-published' capability dev.gitlive:firebase-auth:1.3.1 declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_simulator_arm64')
          - Variant 'releaseRuntimeElements-published' capability dev.gitlive:firebase-auth:1.3.1 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_simulator_arm64')``
Thanks

**Comment by tiagonuneslx** [comment]
Hi Alex,
Everything is working for me in my M1 Mac, in the latest commit. What Java version are you using?

My Java version:
```
java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment Zulu16.30+15-CA (build 16.0.1+9)
OpenJDK 64-Bit Server VM Zulu16.30+15-CA (build 16.0.1+9, mixed mode, sharing)
```

**Comment by tiagonuneslx** [comment]
The title of this issue may be misleading. This library has full support for Apple M1 Silicon. I can confirm, you can use it and build it on M1 Mac, natively (after v1.4.2 [kotlin 1.5.30]) or through Rosetta 2 (before v1.4.2 [kotlin 1.5.10]).

I'm not sure why you're getting this error though...

**Comment by MartinRajniak** [comment]
Same here (although for Firestore),
I think the issue is that we are trying to run it on M1 Simulator (ios_simulator_arm64),
and (just guessing) this lib does not provide this target?

I had similar issue with coroutines until this has been solved (for reference)
https://github.com/Kotlin/kotlinx.coroutines/issues/2908
