### ISSUE TITLE
Add FirebaseUser.updateProfile to [auth] for [ios/android]

### ISSUE THREAD

**Issue by vanniktech** [GitLiveApp/firebase-kotlin-sdk#23]
| Library               | Class                            | Member                                        | Platforms                  |
| :-----------------| :------------------------ | :----------------------------------- | :---------------------- |
| e.g auth | e.g FirebaseUser | e.g updateProfile  | Android, iOS  |

Currently, one needs to: `.android.updateProfile(UserProfileChangeRequest.Builder().setDisplayName())` which is awkward and can't be done in commonCode.

**Comment by vladimirpetrovski** [comment]
Any update on this? I'm also not able to access anything related to updating the user's profile in the common module.

**Comment by nbransby** [comment]
Not yet, but PRs welcome!

**Comment by vanniktech** [comment]
Feel free to take a stab on this @vladimirpetrovski

**Comment by Daeda88** [comment]
Im making an implementation of this. Hope to have something early next week.
