### ISSUE TITLE
Support Java Admin SDK

### ISSUE THREAD

**Issue by LandryNorris** [GitLiveApp/firebase-kotlin-sdk#235]
I am using the Java Admin SDK on server-side code, and found that many of the extensions in the firestore portion of this repo could easily be ported to the Admin SDK. Presumably most of the others would too, but even if some parts of Firebase couldn't be ported, any of these extensions would be nice to have. This would make server-side interaction with Firebase much nicer.

**Comment by nbransby** [comment]
We now support java clientside environments via the https://github.com/GitLiveApp/firebase-java-sdk

**Comment by ScottPierce** [comment]
@nbransby It'd be nice if there was a way to share code between KMP client-side code, and also Java server code. I believe that's what this ticket was trying to accomplish. Is that possible with this?

**Comment by nbransby** [comment]
No It not possible as its for client-side java environments only - I know some people were using the Java Admin SDK client-side in lieu of a Java SDK so will help in case.
