### ISSUE TITLE
JS Realtime Database truncates children

### ISSUE THREAD

**Issue by thejoeba** [GitLiveApp/firebase-kotlin-sdk#236]
When using the project in JS, I try to collect the values for an object, but the children count is always 1. The same code on Android returns more than 1.

```
Firebase.database.reference("rooms").valueEvents.collect { querySnapshot ->
    console.log("rooms: ${querySnapshot.children.count()}")
}
```

using: firebase-database:1.4.3

**Comment by nbransby** [comment]
are you able to add a failing test for this in a PR? I suspect this is not an issue with the firebase-kotlin-sdk but perhaps the firebase-js-sdk

**Comment by thejoeba** [comment]
Sure, I don't see any unit tests for database jsMain. I'll look for other js tests, but what database would I point to in the PR?

**Comment by nbransby** [comment]
You need to fork the repository and then push the branch to your fork then you can create a pull request to this repo

**Comment by Darkos-den** [comment]
@thejoeba @nbransby I faced the same problem, is there any solution?
