### ISSUE TITLE
IR compiler support?

### ISSUE THREAD

**Issue by Nikola-Milovic** [GitLiveApp/firebase-kotlin-sdk#243]
Any thoughts on supporting the IR compiler, I have a local copy of 1.4.1 and it was rather minimal changes required to get IR support for JS. Haven't tested everything so not sure if it would break something major but don't think so. Quite useful for both Compose and React for web

**Comment by mihbor** [comment]
+1 
IR compiler support is needed to use this lib in conjunction with compose for web.

**Comment by mihbor** [comment]
I created a much more minimalistic PR: https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/268
Tested it locally with firebase-firestore only, but so far so good.
Hope this helps.

**Comment by nbransby** [comment]
closing  as https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/268 was merged
