### ISSUE TITLE
Add [class name].[function name] to [library name] for [platform names]

### ISSUE THREAD

**Issue by azurlake** [GitLiveApp/firebase-kotlin-sdk#258]
| Library               | Class                            | Member                                        | Platforms                  |
| :-----------------| :------------------------ | :----------------------------------- | :---------------------- |
| firestore | DocumentSnapshot | toObject  | Android, iOS  |

I don't know if deserialization can be achieved with a similarly simple and straightforward approach, but this would be a must in a final release. I can't find the toObject member in the current 1.4.3 version.

**Comment by nbransby** [comment]
You can use `kotlinx-serialization` for this, please see https://github.com/GitLiveApp/firebase-kotlin-sdk#serialization

If you don't want to use `kotlinx-serialization` you can always access the platform native `toObject` calls via your `androidMain` and `iosMain`
