### ISSUE TITLE
kotlin.ClassCastException: null cannot be cast to kotlin.collections.Map

### ISSUE THREAD

**Issue by b95505017** [GitLiveApp/firebase-kotlin-sdk#267]
What is the right way to decode DataSnapshot (Firebase realtime database) when the node is empty?
```
dataSnapshot.value<Foo?>()
dataSnapshot.value(Foo.serializer().nullable)
```

I expect it will return `null`, but it throw cast exception instead.

**Comment by nbransby** [comment]
They should both work, what platform is this on? can you submit  PR with a failing test?
