### ISSUE TITLE
IOS Sample App Request

### ISSUE THREAD

**Issue by RZahr** [GitLiveApp/firebase-kotlin-sdk#300]
I saw in the issues section that many developers are requesting this due to the errors they are facing like `ld: framework not found FirebaseFirestore`. Can you please provide a simple sample that we can load on ios and follow to set for our project?

**Comment by gchristov** [comment]
Pulling this out from our discussion in #288. Here are basic setup instructions that worked for us:

### Swift Package Manager Setup

1. Create new Kotlin Multiplatform App from Android Studio (AS version is 2021.2.1, Chipmunk, KMM plugin version is `0.3.2(212-1.6.10-release-974-IJ)-216`)
2. Select `Regular Framework` for the setting `iOS Framework Distribution`
3. Add `classpath("com.google.gms:google-services:4.3.10")` to the dependencies section of `buildscript` under `MyApplication/build.gradle.kts`
4. Add `apply(plugin = "com.google.gms.google-services")` and `implementation(platform("com.google.firebase:firebase-bom:30.0.1"))` to `appAndroid/build.gradle.kts`
5. Add `dependencies { implementation("dev.gitlive:firebase-firestore:1.6.1") }` to `commonMain` in `shared/build.gradle.kts`
6. Set `isStatic = true` in your `shared/build.gradle.kts`
7. Link your `google-services` files to both `androidApp` and `iosApp` as you would usually, following the [Firebase docs](https://firebase.google.com/docs/guides)
8. Open `File -> Add Packages` on Xcode and add `https://github.com/firebase/firebase-ios-sdk`
9. Select `FirebaseFirestore` from the available SDKs, add it to your project and wait until Xcode finishes initialising
10. Make sure to call the relevant `dev.gitlive.Firebase.initialize()` methods for iOS and Android where appropriate in your project before making any calls
11. Both Android and iOS should build successfully now and you should be able to use the SDKs in `commonMain`

**Comment by leoull** [comment]
> I saw in the issues section that many developers are requesting this due to the errors they are facing like `ld: framework not found FirebaseFirestore`. Can you please provide a simple sample that we can load on ios and follow to set for our project?

https://github.com/leoull/KMM-FirebaseAuth

**Comment by carlosgub** [comment]
Hi, I finish to publish an article about this https://medium.com/@carlosgub/how-to-implement-firebase-firestore-in-kotlin-multiplatform-mobile-with-compose-multiplatform-32b66cdba9f7
