### ISSUE TITLE
[iOS] cinterop-FirebaseFirestore not found when building for simulator

### ISSUE THREAD

**Issue by walkingbrad** [GitLiveApp/firebase-kotlin-sdk#326]
`Kotlin 1.6.21`
`Android Studio Chipmunk 2021.2.1. Patch 1`
`KMM plugin 0.3.2(212-1.6.10-release-974-IJ)-216`
`dev.gitlive:firebase-firestore:1.6.1` and am using cocoapods
`Xcode 13.4.1`
`iOS 15.5 simulator`

This issue just popped up for me recently in the past week or two. I did upgrade the gradle plugin and Android Studio recently, but nonetheless:

Building for iOS simulator (X64, Intel Mac) fails with this message: 
> Task :shared:compileKotlinIosX64 FAILED
e: Could not find "dev.gitlive:firebase-firestore-cinterop-FirebaseFirestore" in [{my_project_dir}, /Users/{username}/.konan/klib, /Users/{username}/.konan/kotlin-native-prebuilt-macos-x86_64-1.6.21/klib/common, /Users/{username}/.konan/kotlin-native-prebuilt-macos-x86_64-1.6.21/klib/platform/ios_x64]

Building for iOS device (arm64) works fine.

Possibly related to #325 

What I've tried:
- gradle sync
- invalidate caches & restart

**Comment by walkingbrad** [comment]
Issue luckily gone in `1.6.2` 🙏🏻 📿 

Not sure what the cause was, but I suspect something to do with dependency versions (kotlin specifically) that were updated/fixed in this release.

**Comment by walkingbrad** [comment]
I'm not confident this is a real bug, b/c I've noticed in other instances where building to iOS 15.5 works (maybe on other simulator device types?). I suspect it may be something bad in the cache. So if you're reading this and experience the issue, try clearing caches in Android Studio and/or doing an Xcode clean and/or purging Xcode's DerivedData folder.

**Comment by burntcookie90** [comment]
I am seeing this when attempting to run a basic KMM project (only additions from the template are cashapp-molecule and `"dev.gitlive:firebase-firestore:1.6.2"`.

Getting the following:

```
ld: framework not found FirebaseFirestore
```

I've cleaned everything that could be cleaned with no luck.

**Comment by casvanluijtelaar** [comment]
I'm having the same issue with a basic project using `dev.gitlive:firebase-config:1.6.2`

Getting similar issue:
```
ld: framework not found FirebaseABTesting
```

**Comment by casvanluijtelaar** [comment]
@walkingbrad can you reopen this?

**Comment by walkingbrad** [comment]
While both of your issues seem similar, I don't think they're necessarily the same as mine (which is no longer a reproducible issue for me). So I think those should be new issues if the following does not solve them:

@casvanluijtelaar, in your comment on #233, it looks like there is actually a clear underlying cause pointed out by the second error you posted of `kotlin.NotImplementedError`. I would check if that error string exists in this repo (or find where it is coming from) so you can potentially implement the thing that it is saying needs to be implemented.

@burntcookie90, I would suggest checking out #233 as well. Have you added `FirebaseFirestore` to the `Podfile` on the iOS side?

**Comment by casvanluijtelaar** [comment]
> While both of your issues seem similar, I don't think they're necessarily the same as mine (which is no longer a reproducible issue for me). So I think those should be new issues if the following does not solve them:
> 
> @casvanluijtelaar, in your comment on #233, it looks like there is actually a clear underlying cause pointed out by the second error you posted of `kotlin.NotImplementedError`. I would check if that error string exists in this repo (or find where it is coming from) so you can potentially implement the thing that it is saying needs to be implemented.
> 
> @burntcookie90, I would suggest checking out #233 as well. Have you added `FirebaseFirestore` to the `Podfile` on the iOS side?

the error is being thrown from the Cinterop, not from this package specifically. So I can assume that using remote-config with firebaseABTesting included in the KMM is not supported until there's a solution for that?

**Comment by casvanluijtelaar** [comment]
minimum repoducable example https://github.com/casvanluijtelaar/kmm-firebase-test
