### ISSUE TITLE
Request for 1.6.2 release

### ISSUE THREAD

**Issue by walkingbrad** [GitLiveApp/firebase-kotlin-sdk#330]
I'm in need of a fix I contributed almost three months ago in #297 (thanks @nbransby) because my team is heading into a big launch. This repo hasn't had a new release in a while, so I'm still left with the very apparent bug it fixes.

Apologies if this is not the right place to raise this, but I wasn't sure how else to get in touch. Let me know if/how I can help (testing the release candidate etc).

**Comment by walkingbrad** [comment]
Bump - to be annoying ;)

**Comment by michaelprichardson** [comment]
Hi @walkingbrad, I have released [1.6.2](https://github.com/GitLiveApp/firebase-kotlin-sdk/releases/tag/v1.6.2).

Apologies for the delay!
