### ISSUE TITLE
Add firebase.auth.Auth.Persistence to auth for js

### ISSUE THREAD

**Issue by Darkos-den** [GitLiveApp/firebase-kotlin-sdk#333]
[Authentication State Persistence](https://firebase.google.com/docs/auth/web/auth-state-persistence)

| Library               | Class                            | Member                                        | Platforms                  |
| :-----------------| :------------------------ | :----------------------------------- | :---------------------- |
| auth                  | Persistence                   | -                                                    | js                               |
| auth                  | FirebaseAuth                | setPersistence                               | js                               |

There seems to be no way to save the user's session for the browser right now, which is a critical feature for this platform.

**Comment by MinmoTech** [comment]
Persistence should be automatic, you just need to call
```kotlin
    auth.js.onAuthStateChanged({ user ->
            if (user != null) {
                println("User is signed in")

            } else {
                println("User is signed out")
            }
        })
```

**Comment by Darkos-den** [comment]
Indeed, it seems to be working. I did not know about it, perhaps this question can be closed.

**Comment by mattdornfeld** [comment]
Sorry how does the example shown here illustrate persistence? What if I wanted to selectively enable persisting a user session if a "remember me" checkbox is enabled?
