### ISSUE TITLE
How about updating Firebase BOM? (29.3.0 -> 30.3.2)

### ISSUE THREAD

**Issue by valeriyo** [GitLiveApp/firebase-kotlin-sdk#334]
It's fallen behind:
```
"androidMainImplementation"(platform("com.google.firebase:firebase-bom:29.3.0"))
```

The latest Firebase BOM is `30.3.2`: https://firebase.google.com/support/release-notes/android

**Comment by Bradleycorn** [comment]
Submitted #363  today (which has been merged) that updates android, iOS and js targets to the lastest versions of firebase. In the case of Android, the BOM is updated to 31.4.0.
