### ISSUE TITLE
firebase-storage & firebase-messaging is not deployed on maven

### ISSUE THREAD

**Issue by Murtowski** [GitLiveApp/firebase-kotlin-sdk#336]
Firebase Storage `dev.gitlive:firebase-storage` & `dev.gitlive:firebase-messaging` doesn't exist on Maven - they are not deployed.

https://repo.maven.apache.org/maven2/dev/gitlive/

```
> Could not find dev.gitlive:firebase-storage:1.6.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/dev/gitlive/firebase-storage/1.6.1/firebase-storage-1.6.1.pom
       - https://repo.maven.apache.org/maven2/dev/gitlive/firebase-storage/1.6.1/firebase-storage-1.6.1.pom
```

**Comment by nbransby** [comment]
Yes I am afraid no one has contributed towards the coverage of these modules yet

**Comment by SebastianHelzer** [comment]
With the new changes from #393, what needs to be done in order to deploy storage to Maven?

**Comment by nbransby** [comment]
It will be deployed in the next release that won't be immediate though because the storage work is untested as of yet. If you want to get your hands on it sooner I suggest you fork and build it to maven local and let us know how you get on!

**Comment by nbransby** [comment]
storage now deployed
