### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FIRRemoteConfig

### ISSUE THREAD

**Issue by Kashifmasood07** [GitLiveApp/firebase-kotlin-sdk#340]
I have integrated Remote Config in my shared module but I am getting following errors on iOS side,

`Undefined symbol: _OBJC_CLASS_$_FIRRemoteConfig`
`Undefined symbol: _OBJC_CLASS_$_FIRRemoteConfigSettings`

As far as I have checked, Firebase has moved Remote Config implementation from FIRRemoteConfig to just RemoteConfig, but in your latest update it is still FIRRemoteConfig.
Can you please look in to it, and make the required changes... Thanks.

**Comment by Kashifmasood07** [comment]
I installed 'RemoteConfig' instead of 'FirebaseRemoteConfig'.
Changing it fixed the issue.

**Comment by shubhamsinghshubham777** [comment]
@Kashifmasood07 Could you please explain this a bit more? I'm facing the same issue with a lot of error messages like:
`Undefined symbol: _OBJC_CLASS_$_FIRActionCodeInfo`
`Undefined symbol: _OBJC_CLASS_$_FIRActionCodeSettings`
`Undefined symbol: _OBJC_CLASS_$_FIRApp`
`Undefined symbol: _OBJC_CLASS_$_FIRAuth`
`Undefined symbol: _OBJC_CLASS_$_FIRAuthDataResult`
`Undefined symbol: _OBJC_CLASS_$_FIRAuthTokenResult`
`Undefined symbol: _OBJC_CLASS_$_FIREmailAuthProvider`
`Undefined symbol: _OBJC_CLASS_$_FIRFacebookAuthProvider`
`Undefined symbol: _OBJC_CLASS_$_FIRGitHubAuthProvider`
`Undefined symbol: _OBJC_CLASS_$_FIRGoogleAuthProvider`
`Undefined symbol: _OBJC_CLASS_$_FIRMultiFactorInfo`
`Undefined symbol: _OBJC_CLASS_$_FIRMultiFactorSession`
`Undefined symbol: _OBJC_CLASS_$_FIROAuthProvider`
`Undefined symbol: _OBJC_CLASS_$_FIROptions`
`Undefined symbol: _OBJC_CLASS_$_FIRPhoneAuthProvider`
`Undefined symbol: _OBJC_CLASS_$_FIRTwitterAuthProvider`
`Undefined symbol: _OBJC_CLASS_$_FIRUser`

My project's shared `build.gradle.kts` looks like this:
```
plugins {
    kotlin("multiplatform")
    kotlin("native.cocoapods")
    id("com.android.library")
}

kotlin {
    android()
    iosX64()
    iosArm64()
    iosSimulatorArm64()
    js { browser() }

    cocoapods {
        summary = "Some description for the Shared Module"
        homepage = "Link to the Shared Module homepage"
        version = "1.0"
        ios.deploymentTarget = "14.1"
        podfile = project.file("../ios/Podfile")
        framework {
            baseName = "shared"
            isStatic = true
        }
    }

    val koinVersion = "3.2.0"

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("dev.gitlive:firebase-common:1.6.2")
                implementation("dev.gitlive:firebase-auth:1.6.2")
                implementation("io.insert-koin:koin-core:$koinVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
                implementation("com.arkivanov.decompose:decompose:1.0.0-beta-02")
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
                implementation("io.insert-koin:koin-test:$koinVersion")
            }
        }
        val androidMain by getting {
            dependencies {
                api("io.insert-koin:koin-android:$koinVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4")
            }
        }
        val androidTest by getting
        val iosX64Main by getting
        val iosArm64Main by getting
        val iosSimulatorArm64Main by getting
        val iosMain by creating {
            dependsOn(commonMain)
            iosX64Main.dependsOn(this)
            iosArm64Main.dependsOn(this)
            iosSimulatorArm64Main.dependsOn(this)
        }
        val iosX64Test by getting
        val iosArm64Test by getting
        val iosSimulatorArm64Test by getting
        val iosTest by creating {
            dependsOn(commonTest)
            iosX64Test.dependsOn(this)
            iosArm64Test.dependsOn(this)
            iosSimulatorArm64Test.dependsOn(this)
        }
        val jsMain by getting
        val jsTest by getting
    }
}

android {
    namespace = "com.playtogether.kmp"
    compileSdk = 33
    defaultConfig {
        minSdk = 21
        targetSdk = 33
    }
}

```

Any help would be appreciated.
