### ISSUE TITLE
Add Database.get to database for Android, iOS

### ISSUE THREAD

**Issue by ijtsmith** [GitLiveApp/firebase-kotlin-sdk#355]
| Library               | Class                            | Member                                        | Platforms                  |
| :-----------------| :------------------------ | :----------------------------------- | :---------------------- |
| database | FirebaseDatabase | get  | Android, iOS  |

**Comment by ijtsmith** [comment]
Would like to be able to this:

        dbRef
            .get()
            .addOnCompleteListener { task ->
                val response = if (task.isSuccessful) {
                    val items = task.result.children.mapNotNull {
                        it.getValue(Item::class.java)
                    }
                    Resource.Success<List<Item>>(items)
                } else {
                    Resource.Error<List<Item>>(task.exception?.localizedMessage.toString())
                }
                trySend(response).isSuccess
            }

        awaitClose {
            close()
        }

https://firebase.google.com/docs/database/android/read-and-write#read_once_using_get

**Comment by nbransby** [comment]
you can just use dbRef.snapshots.first()
