### ISSUE TITLE
Project is missing target

### ISSUE THREAD

**Issue by Deaths-Door** [GitLiveApp/firebase-kotlin-sdk#362]
The Firebase Kotlin SDK project and its subprojects(modules) are missing the JVM target that is used for desktop development (using desktop compose ) . It means that this library isn't a true kotlin multiplatform library. Note : I have checked multiple modules for JVM target but it was not found. I would like to see this in the future

**Comment by Deaths-Door** [comment]
(To Open it as it was created on closed issue by default)

**Comment by nbransby** [comment]
We can possibly look into open sourcing our jvm port of firebase-android but would be looking for maintainers

**Comment by Deaths-Door** [comment]
For the JVM port you are meaning using the Firebase Admin SDK right. 
Note : I know this isn't the place but what do i need to add as a dependency in my project as its very unclear ( and also buildgraldes only contain android target)

**Comment by nbransby** [comment]
No it's a port of the firebase-android-sdk to pure java
