### ISSUE TITLE
NullPointerException when decoding sealed class list

### ISSUE THREAD

**Issue by brahyam** [GitLiveApp/firebase-kotlin-sdk#366]
Hi!,

Thanks a lot for the huge effort of making available this library. 

While using the SDK to store a list of sealed classes I ran into the following error on decoding.
`NullPointerException: null cannot be cast to non-null type kotlin.collections.Map<*, *>`

I managed to track it to `firebase-common/androidMain/_decoders.kt` `FirebaseDecoder.structureDecoder` function. (and also its iOS equivalent)

It happens because the descriptor is expecting a `value` property that was not encoded. I managed to fix it with the following
```kotlin
StructureKind.CLASS, StructureKind.OBJECT, PolymorphicKind.SEALED -> (value as Map<*, *>).let { map ->
        FirebaseClassDecoder(decodeDouble, map.size, { map.containsKey(it) }) { desc, index ->
            val elementName = desc.getElementName(index)
            if (desc.kind is PolymorphicKind && elementName == "value") {
                map
            } else {
                map[desc.getElementName(index)]
            }
        }
    }
```
And similar for the iOS but maybe there is a more elegant way?

I created a PR with failing tests that points out the problem.
https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/365

**Comment by nbransby** [comment]
PR has been merged, thanks for your contribution!
