### ISSUE TITLE
Firestore - ServerTimestamp FieldValue updating to infinity.

### ISSUE THREAD

**Issue by anqus** [GitLiveApp/firebase-kotlin-sdk#367]
I'm trying to update a record timestamp on Firestore, using document.update() and FieldValue.ServerTimestamp: 

`
db.collection("users").document(userId).update(Pair("createdDate", FieldValue.serverTimestamp))
`

Which results in a record looking like this on Firestore:

<img width="220" alt="image" src="https://user-images.githubusercontent.com/54314568/230703685-17c1ebc7-8988-4ab4-bde8-8a97e7ebc96a.png">

Am I doing something incorrectly?

**Comment by nbransby** [comment]
I believe this has been fixed in 1.9.0 - please reopen if something is missing

**Comment by mattegoghero** [comment]
To me it still creates infinity, version 2.1.0
