### ISSUE TITLE
Get Started Firebase Firestore from Kotlin Multiplatform App

### ISSUE THREAD

**Issue by Diy2210** [GitLiveApp/firebase-kotlin-sdk#37]
Hello, i start develop simple kotlin multiplatform app, but  I'm new in kotlin develop, how use firebase firestore in common code. I implement library, create app & database in firebase console. Then create firebase helper class. Really lacking guide/tutorial/wiki. Help plz.

![Снимок экрана 2020-06-10 в 11 39 42](https://user-images.githubusercontent.com/9552501/84246324-22819c00-ab0f-11ea-9e2f-1a53f726b8ad.png)

**Comment by nbransby** [comment]
You don't need to add a helper as Firebase.firestore etc is already defined in the SDK.

The usage is exactly the same as the official android SDK except for the differences explained in the README. So try by following the android tutorial from Firebase

**Comment by chrisbln** [comment]
[Here](https://firebase.google.com/docs/firestore/quickstart#kotlin+ktx) is the documentation.
