### ISSUE TITLE
Framework not found FirebaseAuth with version 1.8.1 of library and Kotlin 1.8.20

### ISSUE THREAD

**Issue by Mazqaz** [GitLiveApp/firebase-kotlin-sdk#372]
Cannot build ios project, build fails with error Framework not found FirebaseAuth.
I update library version to 1.8.1 and also update Kotlin version to 1.8.20.

If I use library version 1.6.2 and Kotlin version to 1.7.20 everything work fine and project builds with success.

Error happen if Kotlin version upgraded from 1.7.20. 
How to fix this issue. thanks.

**Comment by walkingbrad** [comment]
There must be a way to solve it while having a dynamically-linked framework, but I didn't figure it out. I would also like to know. 

In the meantime, setting your framework to link statically will probably fix it. Kotlin 1.8 changed the default from static to dynamic, so if you didn't have a line like this before, then you would've been linking statically. 

```
cocoapods {
    ...
    framework {
        ...
        isStatic = true
    }
}
```

There are good performance reasons to link statically, so I'm not sure why the default was changed to dynamic.

**Comment by Mazqaz** [comment]
> There must be a way to solve it while having a dynamically-linked framework, but I didn't figure it out. I would also like to know.
> 
> In the meantime, setting your framework to link statically will probably fix it. Kotlin 1.8 changed the default from static to dynamic, so if you didn't have a line like this before, then you would've been linking statically.
> 
> ```
> cocoapods {
>     ...
>     framework {
>         ...
>         isStatic = true
>     }
> }
> ```
> 
> There are good performance reasons to link statically, so I'm not sure why the default was changed to dynamic.

Thank you!
After adding `isStatic = true` ios project build successfully.
