### ISSUE TITLE
`DoubleAsTimestampSerializer.serverTimestamp` not accessible

### ISSUE THREAD

**Issue by ubuntudroid** [GitLiveApp/firebase-kotlin-sdk#380]
In version 1.8.1 some great new addition to timestamp handling were introduced by @vpodlesnyak. 🙌 

The [docs are describing](DoubleAsTimestampSerializer.serverTimestamp) how to handle server timestamps with `Double`s. However, it looks like `DoubleAsTimestampSerializer.serverTimestamp` is not accessible:

![CleanShot 2023-05-26 at 16 22 40](https://github.com/GitLiveApp/firebase-kotlin-sdk/assets/519867/f49973d2-c334-49d9-a3e4-0fe18b8097c6)

For now, I'm working around this by directly using the value of `DoubleAsTimestampSerializer.serverTimestamp`, which is `Double.POSITIVE_INFINITY`.

**Comment by vpodlesnyak** [comment]
hi. I'm planning to fix it in this [PR](https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/371). cheers

**Comment by nbransby** [comment]
I believe this has been fixed in 1.9.0 - please reopen if something is missing

**Comment by ubuntudroid** [comment]
Indeed, it's working now, many thanks @nbransby ! 🙏
