### ISSUE TITLE
Instruction how to setup and use package with multiplatform Android & iOS app?

### ISSUE THREAD

**Issue by kishieel** [GitLiveApp/firebase-kotlin-sdk#389]
Would it be possible to provide a step-by-step guide on how to install and use this package, along with some basic examples and the necessary configurations needed to use it?

As a new developer in the Kotlin multiplatform environment, I find it extremely difficult to create anything here, and any progress requires hours of googling. Unfortunately, there aren't many helpful guides available for this package or Kotlin multiplatform.

After struggling with the installation of this package for a few days, I encountered the following error:

```
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process tech.carrotly.lettersandnumbers.android. Make sure to call FirebaseApp.initializeApp(Context) first.
```

I'm calling `Firebase.initialize(...)` but it doesn't change anything.

I couldn't find a method like initializeApp exposed by this package. Should I use another package together with this package? I should called this with shared scope/android scope? Is the method called something different from what is mentioned in the error?

I believe that any guide or example would be really helpful for new developers.

**Comment by ahmedsalemelzeiny** [comment]
@kishieel Did you solve it?

**Comment by carlosgub** [comment]
Hi, I finish to publish an article about this Hi https://medium.com/@carlosgub/how-to-implement-firebase-firestore-in-kotlin-multiplatform-mobile-with-compose-multiplatform-32b66cdba9f7
