### ISSUE TITLE
Question: How to deserialize an ID as part of the object using Firestore

### ISSUE THREAD

**Issue by vladimirpetrovski** [GitLiveApp/firebase-kotlin-sdk#39]
Actually I'm not sure if this question is related to this library or the official [Kotlin serialization](https://github.com/Kotlin/kotlinx.serialization) library, but I'll give it a try.

I would like to know if anyone has a better idea of deserializing a `DocumentSnapshot` object that has an `ID` parameter in the path of Firestore object instead of its body.

For example: 
Let's say I have a collection of accounts where every account has its own generated `ID` in the path. I use the Kotlin serialization library to deserialize Firestore data which has a structure like this 👇 
```
"accounts/some_auto_generated_id" {
    fullName: "My name",
    email: "myemail@example.com"
}
```
I have an object for it that looks like this 👇 

```
@Serializable
data class Account(
    val id: String = "",
    val fullName: String = "",
    val email: String = ""
)
```
and I want to grab the path `ID` and put it as part of the object.

👍 My current solution actually copies the object and puts the `ID` explicitly
```
Firebase.firestore
            .collection("accounts/some_auto_generated_id")
            .snapshots
            .map { querySnapshot ->
                querySnapshot.documents.map { documentSnapshot ->
                    documentSnapshot
                        .data(Account.serializer())
                        .copy(id = documentSnapshot.id)
                }
            }
```

**So my question is, is there any better solution for this particular use case?**

Thank in advance!

**Comment by nbransby** [comment]
Hi @vladimirpetrovski, we use the exact same solution in our code - it's the right way to do it.

Maybe we could add support for automatic id deserialization in some form but the native Firebase SDK don't support this either

**Comment by vladimirpetrovski** [comment]
Good to know. Thank you very much for your answer!
