### ISSUE TITLE
Compose multiplatform support (for jvm, macos, wasm, linux etc.)

### ISSUE THREAD

**Issue by dQqAn** [GitLiveApp/firebase-kotlin-sdk#409]
Is there any work on it? 

**Also, some API coverage are not 100%. Can you share what features are supported and not supported in the document?**

**Comment by nbransby** [comment]
You'll need to check the source to see whats covered - look at the commonMain source for the except statements - pretty concise list on whats supported

**Comment by nbransby** [comment]
Compose multiplatform is now supported in release 1.9.0 via the https://github.com/GitLiveApp/firebase-java-sdk

**Comment by nowiwr01w** [comment]
@nbransby Hello, can you share your thoughts about wasm support?
As I can see, it's relevant for some people
https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/426
