### ISSUE TITLE
Failed Resolve 1.8.2

### ISSUE THREAD

**Issue by Deorigami** [GitLiveApp/firebase-kotlin-sdk#414]
Hi there .. thanks for your work .. im working on Full KMP project with firebase .. im waiting For Document Reference Serialization and im happy when 1.8.2 released ..

But i can resolve All dependency for 1.8.2

![Screenshot 2023-08-28 055804](https://github.com/GitLiveApp/firebase-kotlin-sdk/assets/70903634/ca3a4eb6-0f9e-4745-9ce8-1e0184519b86)

**Comment by nbransby** [comment]
Sorry about that, please try 1.9.0

**Comment by Deorigami** [comment]
thank you very much
