### ISSUE TITLE
Firebase Auth not catching errors ?

### ISSUE THREAD

**Issue by JoaoPint0** [GitLiveApp/firebase-kotlin-sdk#419]
```
viewModelScope.launch {
      val result = auth.signInWithEmailAndPassword(
          email = state.email.value,
          password = state.password.value
      )

      val user = result.user
      if (user != null) {
          onSuccess()
      }
  }

```
And the app just crashes for not having that user.

com.google.firebase.auth.FirebaseAuthInvalidUserException: There is no user record corresponding to this identifier. The user may have been deleted.

**Comment by nbransby** [comment]
Read: https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth#signInWithEmailAndPassword(java.lang.String,%20java.lang.String)
And
