### ISSUE TITLE
Upgrade Firebase Android BoM to v32

### ISSUE THREAD

**Issue by MattSkala** [GitLiveApp/firebase-kotlin-sdk#423]
It seems this SDK currently uses an outdated version of Firebase BoM 31.4.0 (March 2023) on Android. It should be updated to the latest available version of 32.3.1. 

The latest BoM release includes several new features and bug fixes, including https://github.com/firebase/firebase-android-sdk/issues/5266

**Comment by Qw4z1** [comment]
Just FYI, #375 is a semi-active PR which does the same thing. No clue when it will be merged though (I'm not one of the maintainers). =)
