### ISSUE TITLE
Firebase Functions https backend API

### ISSUE THREAD

**Issue by chrisbln** [GitLiveApp/firebase-kotlin-sdk#43]
The Firebase Functions https backend API is not yet implemented. Do you think to integrate this API into your project?

For example:
```
val app = express()
app.get("") { _, res ->
    res.status(200).send("hello")
}
exports.hello = functions.https.onRequest(app)
```

I could integrate parts of my small library https://github.com/chrisbln/kotlin-firebase-functions

**Comment by nbransby** [comment]
Hey @chrisbln,

Well the goal of this library is to be a multiplatform wrapper around the firebase client libraries. I think it would probably make sense to keep a backend library separate.

**Comment by chrisbln** [comment]
Ah I understand, I didn't recognize it the first time ;)
