### ISSUE TITLE
Is offline data automatically synced when device comes online?

### ISSUE THREAD

**Issue by j-roskopf** [GitLiveApp/firebase-kotlin-sdk#443]
According to the Firestore [documentation](https://firebase.google.com/docs/firestore/manage-data/enable-offline)

`When the device comes back online, Cloud Firestore synchronizes any local changes made by your app to the Cloud Firestore backend.`

Is that functionality present in this SDK as well?

Thanks!

**Comment by nbransby** [comment]
Yes as we just use the appropriate native sdk under the hood.

Note: Offline persistence is supported only in Android, Apple, and web apps.
