### ISSUE TITLE
[Bug] Coroutines version

### ISSUE THREAD

**Issue by DatL4g** [GitLiveApp/firebase-kotlin-sdk#474]
The coroutines version is highly outdated.
As mentioned by the developers it's required that the version match. (Small version changes do not matter to my experience)

> Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'

Used version in this project: 1.7.3
Used version in java-sdk: 1.6.4

**Latest available version:** 1.8.0

Please update the dependencies as this breaks the compatibility with a new compose app.

**Comment by nbransby** [comment]
Fixed in https://github.com/GitLiveApp/firebase-java-sdk/releases/tag/v0.4.0
