### ISSUE TITLE
How can i implement google signIn?

### ISSUE THREAD

**Issue by alexgallardo11** [GitLiveApp/firebase-kotlin-sdk#475]
How can I add Google login? Does the access token have to be implemented for each platform independently, or is there a way to do it with this library?

**Comment by Qw4z1** [comment]
The platform specific implementations of different providers are not part of Firebase, so I assume it's out of scope for this library.

That said, there are [this library](https://medium.com/@mirzemehdi/kmpauth-kotlin-multiplatform-authentication-library-a6d23fd83cb5) that you can use or take inspiration from to get the Credentials you need to pass to Firebase.

**Comment by nbransby** [comment]
Yes you need to implement that yourself foe each platform via https://github.com/GitLiveApp/firebase-kotlin-sdk?tab=readme-ov-file#accessing-the-underlying-firebase-sdk
