### ISSUE TITLE
Add firebase-ui-auth for multiplatform?

### ISSUE THREAD

**Issue by DJ-Glock** [GitLiveApp/firebase-kotlin-sdk#477]
| Library  | Class            | Member               | Platforms        |
|:---------|:-----------------|:---------------------|:-----------------|
| firebase-ui-auth | - | e.g signInWithGithub | multiplatform |

Hi all
I am not very experienced developer. I'm trying to implement Firebase Authentication via Google account for compose multiplatform. I tried to add `firebase-ui-auth`, but it depends on `com.google.firebase:firebase-auth`. So it looks like I need an dev.gitlive implementation of firebase-kotlin-sdk, that uses dev.gitlive:firebase-auth.

Do you have any plan implementing this module?

**Comment by teamhubuser** [comment]
No as its platform specific, but it doesn't stop you using it directly on Android yourself though, `dev.gitlive:firebase-auth` already depends on `com.google.firebase:firebase-auth` on android

**Comment by DJ-Glock** [comment]
I see. Thank you.
