### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by tomu28** [GitLiveApp/firebase-kotlin-sdk#480]
Hello firebase-kotlin-sdk Team,

I hope this message finds you well. With the upcoming App Store requirement for all apps and SDKs to include a privacy manifest starting May 1, 2024, I wanted to reach out and ask about any plans your team might have to support this new mandate. As developers who rely on your SDK, this update is crucial for us to ensure we're compliant with the App Store's latest guidelines and can continue offering our services smoothly.

- Reference: https://developer.apple.com/news/?id=3d8a9yyh

Incorporating a privacy manifest into your SDK would not only assist your partners and developers but also contribute to the App Store's broader initiative to improve user privacy. We deeply appreciate the development and support you've provided so far, and we're eager to hear how you plan to tackle this upcoming requirement.

Could you kindly share any updates or intentions regarding the adoption of the privacy manifest in your SDK? We would greatly appreciate your prompt feedback and any guidance you can offer on this matter.

Thank you for your continued support and partnership.

Best regards,

- https://developer.apple.com/support/third-party-SDK-requirements/
- https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by nbransby** [comment]
A draft PR for this would speed things up!

**Comment by tomu28** [comment]
I'm sorry!
There was no need to address this issue as it is resolved solely by complying with the Privacy Manifest at https://github.com/firebase/firebase-ios-sdk . 
I will close this issue.
