### ISSUE TITLE
Access underlying platform-specific APIs

### ISSUE THREAD

**Issue by tgyhlsb** [GitLiveApp/firebase-kotlin-sdk#483]
I'm trying to create extensions on types that are missing some methods.

My understanding is that any `commonMain` type has a `.ios` property that I can use from `iosMain`. I've found such property but I'm unable to use it because I can't import the "FIR" type that backs it.

Example:
I'm trying to add a method to `StorageReference`.
In `iosMain` I have:
```kotlin
import dev.gitlive.firebase.storage.StorageReference
import cocoapods.FirebaseStorage.FIRStorageReference // Error: Unresolved reference: cocoapods

actual fun StorageReference.putBytes(data: ByteArray) {
    println(this.ios.name()) // Error: Unresolved reference: name
}
```

How am I supposed to import and access `FIRStorageReference` properties?

**Comment by nbransby** [comment]
I believe in the case of iOS you need to add the relevant pod to your build.gradle to resolve that, like we have here:
https://github.com/GitLiveApp/firebase-kotlin-sdk/blob/d13f931245a8bfcf390c4cbf5b271f2c1d9aeaa6/firebase-storage/build.gradle.kts#L92
