### ISSUE TITLE
Add addOnSuccessListener and addOnFailureListener for Firestore

### ISSUE THREAD

**Issue by florianNgbala** [GitLiveApp/firebase-kotlin-sdk#485]
Thanks for this lib ! 

Would it be possible to add `addOnSuccessListener` `addOnFailureListener` for the **firestore** "write" methods ? 

I need a way to know if a "write" request has failed or succedded and theses methods seems, to answer my use case 😃

**Comment by nbransby** [comment]
Have a read of https://github.com/GitLiveApp/firebase-kotlin-sdk?tab=readme-ov-file#suspending-functions

The call will throw if it fails
