### ISSUE TITLE
1.12.0 not published?

### ISSUE THREAD

**Issue by valeriyo** [GitLiveApp/firebase-kotlin-sdk#488]
Looks like 1.12.0 (https://github.com/GitLiveApp/firebase-kotlin-sdk/releases/tag/v1.12.0) didn't make it?

https://central.sonatype.com/artifact/dev.gitlive/firebase-database
https://central.sonatype.com/artifact/dev.gitlive/firebase-firestore

the latest version is 1.11.1

**Comment by nbransby** [comment]
Yeah the CI failed :( Hopefully we'll get it published today
