### ISSUE TITLE
Build Error on IOS

### ISSUE THREAD

**Issue by assadyouness** [GitLiveApp/firebase-kotlin-sdk#490]
Undefined symbols for architecture arm64:
  "_FIRAuthErrorDomain", referenced from:
      _cocoapods_FirebaseAuth_FIRAuthErrorDomain_getter_wrapper0 in sharedApp[arm64][22](libdev.gitlive:firebase-auth-cinterop-FirebaseAuth-cache.a.o)
  "_OBJC_CLASS_$_FIRAuth", referenced from:
       in sharedApp[arm64][2714](libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRAuthDataResult", referenced from:
       in sharedApp[arm64][2714](libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRFacebookAuthProvider", referenced from:
       in sharedApp[arm64][2714](libdev.gitlive:firebase-auth-cache.a.o)
  "_OBJC_CLASS_$_FIRGoogleAuthProvider", referenced from:
       in sharedApp[arm64][2714](libdev.gitlive:firebase-auth-cache.a.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbol: _FIRAuthErrorDomain
Undefined symbol: _OBJC_CLASS_$_FIRAuth
Undefined symbol: _OBJC_CLASS_$_FIRAuthDataResult
Undefined symbol: _OBJC_CLASS_$_FIRFacebookAuthProvider
Undefined symbol: _OBJC_CLASS_$_FIRGoogleAuthProvider

**Comment by Daeda88** [comment]
Can you share your `build.gradle`. Make sure your project adds the FirebaseAuth cocoapod dependency with version `10.23.0`.

**Comment by assadyouness** [comment]
right after I added it, it worked thank you
