### ISSUE TITLE
How to upload files to Firebase Storage?

### ISSUE THREAD

**Issue by KhubaibKhan4** [GitLiveApp/firebase-kotlin-sdk#522]
I wanna upload files to firebase but unable to because It requires the File to upload not the byte array, If i try to convert that using java.io in the android & ios code as well but I'm unable to provide me way.

**Comment by BasBuijsen** [comment]
Currently only uploading of files from urls is covered. On the Android side you have a constructor for File that needs a URI to a local file. On the iOS side there is a constructor for File that needs a NSURL to a local file.

However i am currently working on adding metadata to uploading files and that pr will also include uploading data directly (i need it for testing purposes). This will have a constructor on Android with a ByteArray and on iOS with NSData. I am currently working on it so it is not [in the PR](https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/514) yet but it will come soon.

**Comment by KhubaibKhan4** [comment]
That's great. Looking forward to it.

**Comment by BasBuijsen** [comment]
It is merged now so in the next version this should be available 🎉

**Comment by SirFilbido** [comment]
Hello everyone, I believe this solution has already been merged, but I still don't understand how to use it and if there is any recommendation.

On the commonMain side I have the file in ByteArray, I know I need to "convert" it to URI on Android and NS for iOS and then generate the Firebase SDK File to send it to Storage.

What is the recommendation or solution to do this "conversion" from ByteArray to URI/NS?

**Comment by Ashkan-san** [comment]
i also dont understand how to do it. i am trying to upload a PlatformFile from FileKit, but I dont know how to convert that to a File or Data object, which the storage api provides with putData and putFile...

**Comment by SirFilbido** [comment]
> i also dont understand how to do it. i am trying to upload a PlatformFile from FileKit, but I dont know how to convert that to a File or Data object, which the storage api provides with putData and putFile...

I abandoned this approach and went for something simpler that didn't involve other libs. I believe this type of solution could be in the documentation. I don't know if you came to this same solution, but what I did was to do these conversions via channel/native.

In this case, I created one function that will be implemented in androidMain and iosMain

```kotlin
expect fun createTempFileFromByteArray(fileByteArray: ByteArray): File
``` 


androidMain file
```kotlin
actual fun createTempFileFromByteArray(fileByteArray: ByteArray): File {
    val tempFile = java.io.File.createTempFile("temp", null)

    FileOutputStream(tempFile).use { outputStream ->
        outputStream.write(fileByteArray)
    }

    return File(Uri.fromFile((tempFile)))
}
``` 

iosMain file
```kotlin
@OptIn(ExperimentalForeignApi::class)
actual fun createTempFileFromByteArray(fileByteArray: ByteArray): File {
    val tempDirectory = NSTemporaryDirectory()
    val fileName = "temp_${NSUUID().UUIDString}.tmp"
    val tempFilePath = tempDirectory + fileName

    val nsData = fileByteArray.usePinned { pinned ->
        NSData.dataWithBytes(pinned.addressOf(0), fileByteArray.size.toULong())
    }

    val fileUrl = NSURL.fileURLWithPath(tempFilePath)

    val success = nsData.writeToURL(fileUrl, atomically = true)
    if (!success) {
        throw IllegalStateException("Failed to write byte array to file")
    }

    return File(fileUrl)
}
``` 

Function that manages sending to Firebase Storage
```kotlin
suspend fun sendFile(fileUpdate: FileUpdate): String {

        val storageRef = storageReference.child(createLocation(fileUpdate))

        authentication.authenticateUser()

        storageRef.putFile(createTempFileFromByteArray(fileUpdate.fileData))

        return storageRef.getDownloadUrl()
    }
```

**Comment by abdallahmehiz** [comment]
what about jvm?
