### ISSUE TITLE
Use explicit API mode

### ISSUE THREAD

**Issue by nbransby** [GitLiveApp/firebase-kotlin-sdk#535]
With explicit API mode, you must:

Add visibility modifiers to your declarations to make them public, instead of relying on the default public visibility. This ensures that you've considered what you're exposing as part of the public API.

Define the types for all your public functions and properties to prevent unintended changes to your API from inferred types.

https://kotlinlang.org/docs/whatsnew14.html#explicit-api-mode-for-library-authors

**Comment by nbransby** [comment]
@Daeda88 this would help with ensuring we don't unintentionally expose internal APIs as we still need to fix [this](https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/494#issuecomment-2094271428) (waiting for you response there btw)

**Comment by Daeda88** [comment]
Great. I have a branch forked from my k2 brach that adds the binary compatibility validation. On holiday this week but I can add this to it when back. Will pr that branch once k2 is merged, but since I also added ktlint it's rather big so keeping it separate for readability

**Comment by nbransby** [comment]
That would be great!
