### ISSUE TITLE
Analytics package is missing from Maven

### ISSUE THREAD

**Issue by wongcain** [GitLiveApp/firebase-kotlin-sdk#541]
I get an error including the dependency in my Gradle config:
[dev.gitlive:firebase-analytics:1.12.0](https://search.maven.org/artifact/dev.gitlive/firebase-analytics/1.12.0/pom)

Also the link listed on your readme is returning a 404 error:
[dev.gitlive:firebase-analytics:1.12.0](https://search.maven.org/artifact/dev.gitlive/firebase-analytics/1.12.0/pom)

**Comment by BasBuijsen** [comment]
This dependency is not deployed yet. It was merged after the last release so it will be available in the next version that will be released (probably 1.13.0). I have no idea on when this might be, but @nbransby may be able to tell :).

**Comment by LimbaApp** [comment]
It seems that publish workflow for 1.13.0 failed:
https://github.com/GitLiveApp/firebase-kotlin-sdk/actions/runs/9611108925

**Comment by jmiecz** [comment]
https://github.com/GitLiveApp/firebase-kotlin-sdk/actions/runs/9611108925
https://central.sonatype.com/artifact/dev.gitlive/firebase-analytics/1.13.0?smo=true
Looks like the publish workflow went through now but isnt on maven

**Comment by wongcain** [comment]
1.13.0 is working for me now
