### ISSUE TITLE
1.13.0 firebase-common-internal missing?

### ISSUE THREAD

**Issue by jmiecz** [GitLiveApp/firebase-kotlin-sdk#544]
When updating my app to use the new 1.13.0, I am getting an error that it cant find:
Failed | https://dl.google.com/dl/android/maven2/dev/gitlive/firebase-common-internal/1.13.0/firebase-common-internal-1.13.0.pom

Failed | https://repo.maven.apache.org/maven2/dev/gitlive/firebase-common-internal/1.13.0/firebase-common-internal-1.13.0.pom | 252 ms | 0 B | 0 B/s

Failed | https://maven.pkg.jetbrains.space/public/p/compose/dev/dev/gitlive/firebase-common-internal/1.13.0/firebase-common-internal-1.13.0.pom | 545 ms | 0 B | 0 B/s

**Comment by kaidotarma** [comment]
Looks like some internals have been moved to a new location (firebase-common-internal), which was not released.
@Daeda88

**Comment by Reedyuk** [comment]
Looks like the scripts were not adjusted to publish the new internal library.

**Comment by Daeda88** [comment]
Yep, got a PR to fix it in #545 Stupid omision. Unfortunately I dont have merge/publish rights so someone else needs to pick up the rest

**Comment by Reedyuk** [comment]
I've published it now, should take 30 mins - 1hr till its live
