### ISSUE TITLE
1.13.0 FirebaseFirestoreException: initializeFirestore() has already been called with different options

### ISSUE THREAD

**Issue by HansHolz09** [GitLiveApp/firebase-kotlin-sdk#551]
After upgrading to 1.13.0 I get the following error in Web/JS: 
`FirebaseFirestoreException: FAILED_PRECONDITION: initializeFirestore() has already been called with different options. To avoid this error, call initializeFirestore() with the same options as when it was originalIy called, or call getFirestore() to return the already initialized instance.`

**Comment by nbransby** [comment]
Do you add a failing test for this? Or a minimal reproducer to this issue?

**Comment by Daeda88** [comment]
Fixed in #562
