### ISSUE TITLE
1.13.0 Enabling/disabling Firestore network causes a crash on iOS

### ISSUE THREAD

**Issue by kaidotarma** [GitLiveApp/firebase-kotlin-sdk#552]
Looks like version 1.13.0 created a new issue where:
Firebase.firestore.enableNetwork()
or 
Firebase.firestore.disableNetwork()
would cause an app to crash:
`*** Terminating app due to uncaught exception 'FIRIllegalStateException', reason: 'Firestore instance has already been started and its settings can no longer be changed. You can only set settings before calling any other methods on a Firestore instance.'`

The reason seems to be that firestoreSettings gets recreated when this function is called.

This was not an issue in version 1.12.0.
The issue does not reproduce in Android app (1.13.0).

**Comment by kaidotarma** [comment]
Might be related to https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/551

**Comment by kaidotarma** [comment]
Might be related to https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/554

**Comment by nbransby** [comment]
Do you add a failing test for this? Or a minimal reproducer to this issue?

**Comment by kaidotarma** [comment]
@nbransby here is a minimal reproducer repo:
https://bitbucket.org/kaidotarma/firestore_example/src/master/

Last commit has the crash enabled: https://bitbucket.org/kaidotarma/firestore_example/commits/5f1bf79a42e34a4c706d4221350048a5ea282f9a

iOS works with version 1.12.0, but crashes with 1.13.0 - when enableNetwork or disableNetwork is clicked.

**Comment by royneely** [comment]
+1 Also seeing this error on iOS. But not on Android

**Comment by kaidotarma** [comment]
Looks like the same issue happens with terminate() and clearPersistence(). Updated the sample project to include these functions.

**Comment by kaidotarma** [comment]
@nbransby Bump :)

**Comment by nbransby** [comment]
@Daeda88 could this be to do with the changes made in https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/450 ?

**Comment by Daeda88** [comment]
Could be, I'll have a look asap

**Comment by Daeda88** [comment]
@kaidotarma can you share a minimum reproducible code. Enablling/disabling the network works fine for me in a test case. The only reason I can see it not working is if you apply settings after changing the network state. This would probably not have crashed in 1.12 or lower, but that was actually hiding the settings not being applied at all.

**Comment by kaidotarma** [comment]
@Daeda88 did you try running: https://bitbucket.org/kaidotarma/firestore_example/src/master/

**Comment by Daeda88** [comment]
Okay, I understand the problem, trying to get a fix asap.

**Comment by Daeda88** [comment]
#562 should fix it I expect
