### ISSUE TITLE
Add DatabaseReference.get and addValueEventListener to Database for Android, iOS

### ISSUE THREAD

**Issue by murfel** [GitLiveApp/firebase-kotlin-sdk#557]
| Library  | Class            | Member               | Platforms        |
|:---------|:-----------------|:---------------------|:-----------------|
| Database | DatabaseReference | get, addValueEventListener | Android, iOS |

Is there any API to read from the Firebase Realtime Database? It seems that neither `get()`, nor `addValueEventListener()` are available, which are the two options presented in the official tutorial.

Any way to read from Firebase Realtime Database would work for me. Let me know if I'm missing something that already exists!

https://firebase.google.com/docs/database/android/read-and-write

Alternatively, could you point me to how to implement it myself in my application? Where do I put expected/actual? How hard would that be from just forwarding native implementations versus having to think?

**Comment by nbransby** [comment]
Hi @murfel see https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/543

**Comment by murfel** [comment]
@nbransby sorry, my question was about Firebase Realtime Database, not Cloud Firestore realtime updates :) Confusing names!

Just about any way to read from Firebase Realtime Database would work for me!

**Comment by nbransby** [comment]
These links apply for rtdb:
https://github.com/GitLiveApp/firebase-kotlin-sdk?tab=readme-ov-file#flows
https://gitliveapp.github.io/firebase-kotlin-sdk/firebase-database/dev.gitlive.firebase.database/-query/value-events.html
