### ISSUE TITLE
Help connect dev.gitlive:firebase-database to project

### ISSUE THREAD

**Issue by Diy2210** [GitLiveApp/firebase-kotlin-sdk#57]
Hi, I'm new to kotlin multiplatforms, I'm trying to connect **dev.gitlive:firebase-database:0.2.3** in **gradle** to my **multiplatform project**, but I get an error on how to do it right?

 Gradle
![Снимок экрана 2020-07-10 в 11 41 11](https://user-images.githubusercontent.com/9552501/87135933-71078f00-c2a3-11ea-94bf-1da34a806140.png)
![Снимок экрана 2020-07-10 в 11 41 04](https://user-images.githubusercontent.com/9552501/87135942-74027f80-c2a3-11ea-85e3-82d1b082a522.png)
![Снимок экрана 2020-07-10 в 11 50 41](https://user-images.githubusercontent.com/9552501/87136051-998f8900-c2a3-11ea-9eb8-6a83a83f952b.png)

Error:
![Снимок экрана 2020-07-10 в 11 40 47](https://user-images.githubusercontent.com/9552501/87135945-75cc4300-c2a3-11ea-8f02-0b725a13acb4.png)

**Comment by nbransby** [comment]
Hi sorry about that. The CI didn't publish the artifacts correctly. Should be good now but it's version 0.2.0 you need
