### ISSUE TITLE
Google Sign In

### ISSUE THREAD

**Issue by dinesh-thiyagarajan** [GitLiveApp/firebase-kotlin-sdk#576]
Does this support Google sign in for android and iOS modules ? is there anywhere I can find clear documentation of usage of API's ? I couldn't find any

**Comment by santyas** [comment]
@dinesh-thiyagarajan Did you find any good example using google auth button?

**Comment by Qw4z1** [comment]
As usual, you can follow the official Firebase documentation to implement Google and Apple signin. 

That said, if you are using Compose, I recommend checking out  [KMPAuth](https://github.com/mirzemehdi/KMPAuth). It has ready made buttons for both and works with Firebase-kotlin-sdk out of the box.

**Comment by shalva97** [comment]
@Qw4z1 Hi. do you know other alternatives? KMPAuth has issues with Apple login

**Comment by Qw4z1** [comment]
> @Qw4z1 Hi. do you know other alternatives? KMPAuth has issues with Apple login

The official Firebase docs. 😇 Or open an issue in KMPAuth with the bug/bugs you've found? The maintainer is a good guy, so he can probably fix the bug if you give him enough information. 

In my experience, though, the issues usually aren't client side. But rather misconfiguration in Firebase or in Apple Developer.

**Comment by santyas** [comment]
@Qw4z1 KMPAuth author may respond to you soon, he actively maintains the library :)

**Comment by Qw4z1** [comment]
> @Qw4z1 KMPAuth author may respond to you soon, he actively maintains the library :)

Why would he respond to me? I'm not the one with issues. 😅

**Comment by shalva97** [comment]
okay, hoping for the best. 🚀
