### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_FIRAnalytics

### ISSUE THREAD

**Issue by marenovakovic** [GitLiveApp/firebase-kotlin-sdk#585]
### Version 1.13.0 for auth, analytics, firestore and storage
When trying to run app on iOS getting:
- Undefined symbol: _OBJC_CLASS_$_FIRAnalytics
- Linker command failed with exit code 1 (use -v to see invocation)

### Version 1.13.0 for analytics and 1.12.0 for auth, firestore and storage
Getting 15 issues.

Linked FirebaseiOS is 10.26.0 and it works fine without analytics with both 1.13.0 and 1.12.0.

**Comment by marenovakovic** [comment]
My bad. I thought I added Analytics package to iOS app but I haven't.
Everything works fine.

**Comment by marenovakovic** [comment]
Even with added FirebaseAnalytics still getting same errors

**Comment by allenwhite** [comment]
I am also getting this error in our Multiplatform project.

**Comment by Reedyuk** [comment]
Do you have a reproducer sample project?

**Comment by marenovakovic** [comment]
No. I moved on to 2.0.0 and 2.1.0 and there are no problems.
