### ISSUE TITLE
Lower Android minSdk

### ISSUE THREAD

**Issue by zt64** [GitLiveApp/firebase-kotlin-sdk#591]
Hi,

I noticed that the library's min SDK version was raised to 23 in this [commit](https://github.com/GitLiveApp/firebase-kotlin-sdk/commit/267bfd14ae1af8ef1f033ae90cbb5cbd7a2bd393).

It seems like this change might have been made by mistake. The commit message mentions Android 14's restriction on apps with a `targetSdk` lower than 23. However, this restriction only applies to the `targetSdk` of the app, not the `minSdk` of the library.

Wouldn't it make more sense to revert the min SDK version change as it was (at 19) and let the application itself decide on the appropriate target SDK? Raising the `minSdk` to 23 unnecessarily limit the library's compatibility with apps that support older Android versions.

**Comment by nbransby** [comment]
What do you think @Daeda88 ?

**Comment by Daeda88** [comment]
I can have a look. I'd swear I had issues with it, but it might have just been the tests not running on Android 14.

Regardless, the Firebase SDK is at min level 21 so we cannot go lower than that https://github.com/firebase/firebase-android-sdk/blob/main/sdkProperties.gradle

**Comment by Daeda88** [comment]
Got a semi fix in #594 However the auth module will remain at API 23 as that is there the native Android api is at (see https://github.com/firebase/firebase-android-sdk/issues/5927).

**Comment by zt64** [comment]
Ah okay, so I wasn't completely wrong. I appreciate the quick response
