### ISSUE TITLE
OAuthProvider android property is unaccessible in 2.0.0

### ISSUE THREAD

**Issue by mr-kew** [GitLiveApp/firebase-kotlin-sdk#602]
I can't access `android` property of `OAuthProvider` anymore, guess the [#504](https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/504) did break it.

```
import dev.gitlive.firebase.auth.OAuthProvider
import dev.gitlive.firebase.auth.android // Greyed out

fun test(provider: OAuthProvider) {
    val androidProvider = provider.android // Error: Cannot access 'android': it is internal in 'OAuthProvider'
}
```

**Comment by nbransby** [comment]
@Reedyuk did we miss this one?

**Comment by Reedyuk** [comment]
![wtf-monkey](https://github.com/user-attachments/assets/6f21b700-9991-4165-bf88-60e512a908d0)

**Comment by Reedyuk** [comment]
Looks to be here: 
https://github.com/GitLiveApp/firebase-kotlin-sdk/blob/650ff89e15e5dae28afde4c22c65721374a5bb3c/firebase-auth/src/androidMain/kotlin/dev/gitlive/firebase/auth/credentials.kt#L55

**Comment by Reedyuk** [comment]
I wonder if the import is not right?
```
import dev.gitlive.firebase.auth.OAuthProvider.android
```

**Comment by mr-kew** [comment]
> I wonder if the import is not right?
> 
> ```
> import dev.gitlive.firebase.auth.OAuthProvider.android
> ```
It just says directly on the import: 

`Cannot import 'android', functions and properties can be imported only from packages or object`

**Comment by mr-kew** [comment]
@Reedyuk The intellisense also seems to see it, but the import does not work for some reason. It almost feels like some kind of compiler bug
![image](https://github.com/user-attachments/assets/b4fa4980-63d3-462b-857d-48a56dd022bf)

**Comment by Reedyuk** [comment]
I'm working on a fix for you

**Comment by Reedyuk** [comment]
https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/603

**Comment by Reedyuk** [comment]
its in version 2.1.0

**Comment by mr-kew** [comment]
Thank you, I am already using 2.1.0 and it works like a charm
