### ISSUE TITLE
ld: framework 'FirebaseRemoteConfig' not found

### ISSUE THREAD

**Issue by Monabr** [GitLiveApp/firebase-kotlin-sdk#608]
When I am starting build i receive the error: `ld: framework 'FirebaseRemoteConfig' not found`

Please fix.

**Comment by Reedyuk** [comment]
You need to include **Google** Firebase Remote Config in your ios app/project

**Comment by Reedyuk** [comment]
Great, going to close this issue then, others will be able to find it for reference. 
The readme should probably be updated for Kotlin Multiplatform novices, to avoid the issue you got.
