### ISSUE TITLE
Add sealed classes support to serialization

### ISSUE THREAD

**Issue by LartyHD** [GitLiveApp/firebase-kotlin-sdk#61]
Could you add support of "sealed" class to the FirebaseDecoder.structureDecoder and FirebaseEncoder.structureEncoder functions?

I would try it with some think like this:
```kotlin
fun FirebaseEncoder.structureEncoder(descriptor: SerialDescriptor, @Suppress("UNUSED_PARAMETER") vararg typeParams: KSerializer<*>): CompositeEncoder = when(descriptor.kind) {
    StructureKind.LIST, PolymorphicKind.SEALED -> mutableListOf<Any?>()
        .also { value = it }
        .let { FirebaseCompositeEncoder(shouldEncodeElementDefault, positiveInfinity) { _, index, value -> it.add(index, value) } }
    StructureKind.MAP -> mutableListOf<Any?>()
        .let { FirebaseCompositeEncoder(shouldEncodeElementDefault, positiveInfinity, { value = it.chunked(2).associate { (k, v) -> k to v } }) { _, _, value -> it.add(value) } }
    StructureKind.CLASS,  StructureKind.OBJECT -> mutableMapOf<Any?, Any?>()
        .also { value = it }
        .let { FirebaseCompositeEncoder(shouldEncodeElementDefault, positiveInfinity) { _, index, value -> it[descriptor.getElementName(index)] = value } }
    else -> TODO("The firebase-kotlin-sdk does not support $descriptor for serialization yet")
}
```
This case is optimized for plain Kotlin.

Unfortunately, I also have some building problems too, so I cannot implement them myself

**Comment by nbransby** [comment]
What are the building problems you are having?

**Comment by LartyHD** [comment]
lint is failing

**Comment by nbransby** [comment]
What lint?

**Comment by LartyHD** [comment]
idk, that's the error message:
```
Execution failed for task ':firebase-firestore:lint'.
> Lint found errors in the project; aborting build.
```

**Comment by nbransby** [comment]
I have not seen this before! is there a way to get the log of lint errors?

**Comment by LartyHD** [comment]
That's the only thing gradle prints out to the console.
Cloud it is possible that it is a problem with Intelijj and I need to use Android Studio?

**Comment by nbransby** [comment]
Ok I recreated the issue by running the lint task directly - what gradle task were you running?

**Comment by LartyHD** [comment]
gradle build in firebase-firestore

**Comment by nbransby** [comment]
Pull latest master - should fix your issue

**Comment by LartyHD** [comment]
Now I have this problem: "Expected function 'runTest' has no actual declaration in module firebase-firestore.iosArm64Test~1 (test) for Native"
![image](https://user-images.githubusercontent.com/23587853/88418400-cb483a00-cde3-11ea-9744-8acabfdaf391.png)

PS: I use Windows 10

**Comment by nbransby** [comment]
The error is the screenshot is different, are you using the master branch? It says not defined for JVM target but there is no JVM target

**Comment by LartyHD** [comment]
Yes I pulled the master branch and merged it with the local changes

**Comment by nbransby** [comment]
What local changes do you have?

**Comment by LartyHD** [comment]
Now I have done, a hard reset to the latest commit on the master branch.
That was my result:
![image](https://user-images.githubusercontent.com/23587853/89635750-cab1a800-d8a7-11ea-9422-1bbef52d4144.png)
![image](https://user-images.githubusercontent.com/23587853/89635787-d7ce9700-d8a7-11ea-9685-01f1191bec67.png)

(I just run firebase-firestore build on IntelliJ 2020.2 Ultimate with Gradle version 5.6.4)

**Comment by nbransby** [comment]
Still complaining about JVM platform which we dont have a target setup for so still have no idea how you are getting this error

**Comment by nbransby** [comment]
I reproduced this error by running  the build task in happens in the task ':firebase-app:compileDebugUnitTestKotlinAndroid' which makes sense as its trying to run uninstrumented android tests on the jvm. Thing is we dont have any uninstrumented android tests and im not sure how to stop it from doing this.

Workaround is to run the assemble task instead, thats what the CI does

**Comment by nbransby** [comment]
btw build is working now too

**Comment by walkingbrad** [comment]
Hey y'all. Is this a fix we can get back into in the pipeline? I just started using this library (which has worked pretty great so far) but there are couple of hitches such as the inability to deserialize to a sealed class (which I might expect is a fairly common expectation today).

**Comment by nbransby** [comment]
closing as support has been added
