### ISSUE TITLE
Firestore: allow to get nullable value from a snapshoot. 

### ISSUE THREAD

**Issue by Monabr** [GitLiveApp/firebase-kotlin-sdk#621]
Hi.

Firestore is non-sql DB so it is expected that `snaphot.get<Long>("SomeField")` may lead to `null` value. But what I see is throwing exception. This is not how it should be designed.  Please allow to get `null` value without throwing exception.

**Comment by nbransby** [comment]
snaphot.get<Long?>("SomeField")

**Comment by nbransby** [comment]
That's more of a standard Kotlin language thing but would be happy to accept a PR for adding something around that to the documentation, wlll close this issue for now
