### ISSUE TITLE
Firestore iOS not initializing properly

### ISSUE THREAD

**Issue by Daeda88** [GitLiveApp/firebase-kotlin-sdk#77]
Hello,

I'm running into an issue with getting Firestore to run on iOS. It seems that `Firebase.firestore(app: someApp)` is failing to initialize properly.

Essentially, I'm running
```
val app = Firebase.initialize() ?: return
NSLog("${app.ios.name}") // prints __DEFAULT_APP
val firestore = Firebase.firestore(app)
NSLog("${firestore.ios.app.name}") // prints null
val document = firestore.document("path/to")
NSLog("${document.path}") // prints null
```

For comparison, I ran the equivalent code directly using the Firebase-ios-sdk (with the same Google-Services.plist etc)
```
FirebaseApp.configure()
NSLog("App %@", FirebaseApp.app()?.name ?? "No name") // prints __DEFAULT_APP
guard let app = FirebaseApp.app() else { return }
let firestore = Firestore.firestore(app: app)
NSLog("Firestore App %@", firestore.app.name)  // prints __DEFAULT_APP
let document = firestore.document("path/to")
NSLog("Document %@", document.path) // prints path_to
```

Looking at the source code of the library, I dont see any clear reasons what could be causing it.
I've tried a bunch of things myself, including upgrading the SDK to the latest ios builds (when I get this working I can make a PR for that)

The most likely suspect for me at this moment is importing the .framework files into XCode. Seeing as this is not written out clearly in the README.md, I've written my own solution using Carthage:

```
// shared/build.gradle

kotlin {
    // Initialize
    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(kotlin("stdlib-common", kotlinVersion))
                // Common Deps

                implementation("dev.gitlive:firebase-firestore:$commonFirebaseVersion")
                implementation("io.ktor:ktor-client-serialization:$ktorVersion")

            }
        }
    }

    cocoapodsext {
        summary = "summary"
        homepage = "homepage"
        framework {
            isStatic = false
            val carthageBinaries =
                File("${projectDir.absolutePath}/src/iosMain/c_interop/Carthage/Build/iOS").absolutePath
        linkerOpts("-F$carthageBinaries")
}
```

```
# Cartfile
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" ~> 6.17.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" ~> 6.17.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json" ~> 6.17.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json" ~> 6.17.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFunctionsBinary.json" ~> 6.17.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseInAppMessagingBinary.json" ~> 6.17.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBinary.json" ~> 6.17.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMessagingBinary.json" ~> 6.17.0
```

Any advice on what I could be doing wrong? Some help would be greatly appreciated.

Thanks

**Comment by nbransby** [comment]
Hmm that is odd, tbh we are waiting for Kotlin/Native to mature a little more before we try and get iOS working properly - for example I've had to disable the iOS unit tests as we simply can't find a way to get them to run.

Things might get better now 1.4 is released and updating this project to use 1.4 is probably the best place to start to address these issues

**Comment by avdyushin** [comment]
Adding `linkerOpts("-ObjC")` into `cocoapodsext/framework` section and keep `isStatic = false` does work for me

**Comment by nbransby** [comment]
Closing as should be working now https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/78 merged in
