### ISSUE TITLE
Kotlin 1.4.0

### ISSUE THREAD

**Issue by vanniktech** [GitLiveApp/firebase-kotlin-sdk#81]
Do we need to update anything?

**Comment by Daeda88** [comment]
There's no dependencies waiting for an update, so other that updating your build.gradle scripts, I wouldnt expect anything.

**Comment by LissF** [comment]
The `kotlinx.serialization` library has to be updated as well: https://github.com/Kotlin/kotlinx.serialization/issues/993

https://kotlinlang.org/docs/reference/whatsnew14.html#stable-json-serialization
https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md
