### ISSUE TITLE
iOS Setup

### ISSUE THREAD

**Issue by alistairbrightec** [GitLiveApp/firebase-kotlin-sdk#91]
Hi, thanks for this library. Super exciting. I'm keen to use and try to contribute to some of the api coverage.

I have created a KMM project (using 1.4.10 and the new [android studio plugin](https://plugins.jetbrains.com/plugin/14936-kotlin-multiplatform-mobile)) and getting on alright with the Android side. However I don't seem to have access to the iOS implementation. Have I configured it wrong somewhere? 
I know there are some outstanding pr's for 1.4, so maybe that's the reason, but any help would be much appreciated.

```
kotlin {
    android()
    ios {
        binaries {
            framework {
                baseName = "shared"
            }
        }
    }
    sourceSets {
        val commonMain by getting {
            dependencies {
                api("dev.gitlive:firebase-firestore:0.2.0")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9-native-mt")
                implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.1.0")
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
            }
        }
        val androidMain by getting
        val androidTest by getting {
            dependencies {
                implementation(kotlin("test-junit"))
                implementation("junit:junit:4.13")
            }
        }
        val iosMain by getting
        val iosTest by getting
    }
}
```

**Comment by chrisbln** [comment]
@alistairbrightec The Kotlin 1.4.10 is not working with this library at the moment.
See https://github.com/GitLiveApp/firebase-kotlin-sdk/issues/82 

There is a PR https://github.com/GitLiveApp/firebase-kotlin-sdk/pull/90

**Comment by nbransby** [comment]
Closing this as 1.0.0 support 1.4 - can reopen if you are still having issues with 1.0.0

**Comment by alistairbrightec** [comment]
I have now updated to library 1.0.0, but the iOS side of the shared module is still not recognising the dependency.

For example, when I try to use `CollectionReference.ios` it can't find the property. Is there an example setup somewhere I could follow? I'm guessing I've got configuration issues.
