### ISSUE TITLE
Coroutines 1.4.0

### ISSUE THREAD

**Issue by grodin** [GitLiveApp/firebase-kotlin-sdk#98]
Coroutines had a [new release][1] today.

I'm not reporting to request it's immediately upgraded or anything, just to open a tracking issue.

Thanks for all the hard work on this library, it's extremely useful!

[1]:https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.4.0

**Comment by rocketraman** [comment]
1.4.2 is now the latest.
