### ISSUE TITLE
Get tests running in iOS

### ISSUE THREAD

**Issue by nbransby** [GitLiveApp/firebase-kotlin-sdk#99]
Currently the CI doesn't run the iOS tests as we couldn't get them to work at al.

**Comment by nbransby** [comment]
@thoutbeckers are you able to submit a PR for this?

**Comment by thoutbeckers** [comment]
Yes, hopefully this week or next week.

I'll first submit one to make it run locally. I guess Github Action support should not be too hard after that (didn't use it yet).
